{
  "hash": "d86d6e70b5e01a0ab2be6a19bec3e1cb",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Mass, Weight and Density\"\nchapter: 3\nsyllabus-code: \"1.3 Mass and weight; 1.4 Density\"\nauthor: \"Sugeng Riyanto, M.Sc.\"\ndate: \"2026\"\nformat:\n  pdf:\n    toc: false\n    number-sections: true\n  html:\n    toc: true\n    number-sections: true\nexecute:\n  echo: false\n  warning: false\n  message: false\n  cache: true\n  fig-format: png\n  fig-width: 8\n  fig-height: 5\n  dpi: 300\n---\n\n## Learning Objectives\n\nBy the end of this chapter, you will be able to:\n\n**Core Content:**\n\n- State that mass is a measure of the quantity of matter in an object at rest relative to the observer\n\n- State that weight is a gravitational force on an object that has mass\n\n- Define gravitational field strength as force per unit mass; recall and use the equation $g = \\frac{W}{m}$ and know that this is equivalent to the acceleration of free fall\n\n- Know that weights (and masses) may be compared using a balance\n\n- Define density as mass per unit volume; recall and use the equation $\\rho = \\frac{m}{V}$\n\n- Describe how to determine the density of a liquid, of a regularly shaped solid and of an irregularly shaped solid which sinks in a liquid (volume by displacement), including appropriate calculations\n\n- Determine whether an object floats based on density data\n\n**Supplement (Extended):**\n\n- Describe, and use the concept of, weight as the effect of a gravitational field on a mass\n\n- Determine whether one liquid will float on another liquid based on density data given that the liquids do not mix\n\n---\n\n## Mass and Weight: Fundamental Distinctions\n\n### What is Mass?\n\n**Mass** is a measure of the **quantity of matter** in an object at rest relative to the observer.\n\n| Property | Description |\n|:---------|:------------|\n| **SI Unit** | kilogram (kg) |\n| **Nature** | Scalar quantity (magnitude only) |\n| **Invariance** | Independent of location, gravitational field, or shape |\n| **Measurement** | Beam balance or calibrated electronic balance |\n\n**Key Concept:** Mass is an **intrinsic property** of matter. A 10 kg object on Earth has the same mass on the Moon, in orbit, or in deep space.\n\n### What is Weight?\n\n**Weight** is the **gravitational force** acting on an object that has mass.\n\n| Property | Description |\n|:---------|:------------|\n| **SI Unit** | newton (N) |\n| **Nature** | Vector quantity (magnitude and direction) |\n| **Direction** | Always towards the centre of the gravitating body |\n| **Measurement** | Spring balance or calibrated electronic scale |\n\n**Formula:**\n$$W = mg$$\n\nWhere:\n- $W$ = weight (N)\n- $m$ = mass (kg)\n- $g$ = gravitational field strength (N/kg) or acceleration of free fall (m/s²)\n\n### Gravitational Field Strength ($g$)\n\n**Definition:** Gravitational field strength is the gravitational force per unit mass.\n\n$$g = \\frac{W}{m}$$\n\n| Location | $g$ (N/kg) | $g$ (m/s²) |\n|:---------|:-----------|:-----------|\n| Earth (surface) | ≈ 10 | ≈ 10 |\n| Moon (surface) | ≈ 1.6 | ≈ 1.6 |\n| Jupiter (surface) | ≈ 22.9 | ≈ 22.9 |\n| Deep space (far from masses) | ≈ 0 | ≈ 0 |\n\n**Critical Insight:** The numerical equivalence $10 \\text{ N/kg} = 10 \\text{ m/s}^2$ arises because:\n- From $W = mg$: weight causes acceleration $g$ when unopposed\n- From $F = ma$: the same force $W$ produces acceleration $a = g$\n- Therefore, gravitational field strength **is** the acceleration of free fall\n\n::: {.callout-warning}\n**Important:** Weight depends on location; mass does not. An astronaut with mass 70 kg weighs 700 N on Earth but only 112 N on the Moon—yet their mass remains 70 kg in both locations.\n:::\n\n::: {.cell execution_count=2}\n\n::: {.cell-output .cell-output-display}\n![Mass vs weight: how weight changes with gravitational field strength while mass stays constant](03-mass-weight-density_files/figure-docx/fig-mass-vs-weight-planets-output-1.png){#fig-mass-vs-weight-planets fig-align='center'}\n:::\n:::\n\n\n### Measuring Mass vs. Weight\n\n| Instrument | Measures | Principle | Location-Dependent Reading? |\n|:-----------|:---------|:----------|:---------------------------|\n| **Beam balance** | Mass | Compares gravitational forces on object and standard masses | ✗ No (both sides experience same $g$) |\n| **Spring balance** | Weight | Extension proportional to force ($F = kx$) | ✓ Yes (depends on local $g$) |\n| **Electronic balance** | Weight (calibrated to display mass) | Measures force, converts using assumed $g$ | ✓ Yes (requires recalibration for different $g$) |\n\n**Practical Note:** A bathroom scale calibrated for Earth will give an incorrect \"mass\" reading on the Moon because it assumes $g = 10 \\text{ N/kg}$.\n\n---\n\n## Density: Mass per Unit Volume\n\n### Definition and Formula\n\n**Density** ($\\rho$, Greek letter *rho*) is defined as mass per unit volume:\n\n$$\\rho = \\frac{m}{V}$$\n\n| Quantity | Symbol | SI Unit | Common Alternative |\n|:---------|:-------|:--------|:-------------------|\n| Density | $\\rho$ | kg/m³ | g/cm³ |\n| Mass | $m$ | kg | g |\n| Volume | $V$ | m³ | cm³ |\n\n**Conversion:** $1 \\text{ g/cm}^3 = 1000 \\text{ kg/m}^3$\n\n### Densities of Common Substances\n\n::: {.cell execution_count=3}\n\n::: {.cell-output .cell-output-display}\n![Density comparison of common substances (logarithmic scale)](03-mass-weight-density_files/figure-docx/fig-density-comparison-output-1.png){#fig-density-comparison fig-align='center'}\n:::\n:::\n\n\n| Substance | Density (g/cm³) | Density (kg/m³) |\n|:----------|:----------------|:----------------|\n| **Gases** | | |\n| Dry air | 0.00123 | 1.23 |\n| **Liquids** | | |\n| Turpentine | 0.87 | 870 |\n| Olive oil | 0.92 | 920 |\n| Pure water (4°C) | 1.00 | 1000 |\n| Seawater | 1.025 | 1025 |\n| Mercury | 13.6 | 13,600 |\n| **Solids** | | |\n| Polystyrene | 0.016 | 16 |\n| Cork | 0.24 | 240 |\n| Pine wood | 0.50 | 500 |\n| Ice | 0.917 | 917 |\n| Glass | 2.5 | 2500 |\n| Iron | 7.87 | 7870 |\n| Gold | 19.3 | 19,300 |\n\n### Floating and Sinking: The Density Criterion\n\n**Rule:** An object will **float** in a fluid if its **average density** is **less than** the density of the fluid.\n\n$$\\rho_{\\text{object}} < \\rho_{\\text{fluid}} \\quad \\Rightarrow \\quad \\text{Floats}$$\n$$\\rho_{\\text{object}} > \\rho_{\\text{fluid}} \\quad \\Rightarrow \\quad \\text{Sinks}$$\n\n**Why does a steel ship float?**\n- Solid steel ($\\rho \\approx 7.8 \\text{ g/cm}^3$) sinks in water ($\\rho = 1.0 \\text{ g/cm}^3$)\n- A ship contains large volumes of **air** within its hull\n- **Average density** = $\\frac{\\text{total mass}}{\\text{total volume}}$ (steel + air + cargo)\n- If average density < 1.0 g/cm³, the ship floats\n\n::: {.cell execution_count=4}\n\n::: {.cell-output .cell-output-display}\n![Why ships float: average density concept with steel hull and air cavities](03-mass-weight-density_files/figure-docx/fig-ship-buoyancy-output-1.png){#fig-ship-buoyancy fig-align='center'}\n:::\n:::\n\n\n**Example Calculation:**\nA ship has mass $7.68 \\times 10^7 \\text{ kg}$ and dimensions $268 \\text{ m} \\times 32 \\text{ m} \\times 25 \\text{ m}$.\n\n$$V = 268 \\times 32 \\times 25 = 214,400 \\text{ m}^3$$\n$$\\rho_{\\text{avg}} = \\frac{7.68 \\times 10^7}{214,400} = 358 \\text{ kg/m}^3 = 0.358 \\text{ g/cm}^3$$\n\nSince $0.358 < 1.0$, the ship floats.\n\n### Immiscible Liquids: Layering by Density\n\nWhen two or more liquids that **do not mix** (immiscible) are placed in the same container, they arrange themselves in layers according to density:\n\n- **Highest density** → bottom layer\n- **Lowest density** → top layer\n\n**Example:** Mercury ($\\rho = 13.6$), glycerine ($\\rho = 1.26$), water ($\\rho = 1.00$)  \n→ Order from bottom: Mercury → Glycerine → Water\n\n::: {.cell execution_count=5}\n\n::: {.cell-output .cell-output-display}\n![Immiscible liquids layering by density: mercury, glycerine, water](03-mass-weight-density_files/figure-docx/fig-immiscible-liquids-output-1.png){#fig-immiscible-liquids fig-align='center'}\n:::\n:::\n\n\n---\n\n## Practical Measurement Techniques\n\n### Measuring Mass\n\n**Using a Beam Balance:**\n\n1. Place object on left pan\n\n2. Add standard masses to right pan until beam is horizontal\n\n3. Total standard mass = object mass\n\n**Precautions:**\n- ✓ Zero the balance before use\n- ✓ Do not place wet objects directly on the pan\n- ✓ Use a container of known mass for powders/liquids\n\n### Measuring Volume\n\n#### Regular Solids\nUse a metre rule or vernier calipers, then apply geometric formulae:\n\n| Shape | Formula |\n|:------|:--------|\n| Rectangular block | $V = l \\times b \\times h$ |\n| Cylinder | $V = \\frac{\\pi d^2}{4} \\times h$ |\n| Sphere | $V = \\frac{4}{3}\\pi \\left(\\frac{d}{2}\\right)^3$ |\n\n#### Irregular Solids (that sink)\n**Displacement method using a measuring cylinder:**\n\n1. Record initial water volume $V_1$\n\n2. Immerse object completely\n\n3. Record final volume $V_2$\n\n4. Volume of object: $V = V_2 - V_1$\n\n**Precautions:**\n- ✓ Read at the **bottom of the meniscus** at eye level\n- ✓ Remove air bubbles clinging to the object\n- ✓ Lower object gently to avoid splashing\n\n::: {.cell execution_count=6}\n\n::: {.cell-output .cell-output-display}\n![Displacement method for measuring volume of irregular solids](03-mass-weight-density_files/figure-docx/fig-displacement-method-output-1.png){#fig-displacement-method fig-align='center'}\n:::\n:::\n\n\n#### Irregular Solids (that float)\n**Sinker method:**\n\n1. Measure volume of sinker alone: $V_3$\n\n2. Attach floating object to sinker; immerse both\n\n3. Measure combined volume: $V_4$\n\n4. Volume of object: $V = V_4 - V_3$\n\n#### Liquids\n**Using a measuring cylinder or burette:**\n\n1. Find mass of empty container: $m_1$\n\n2. Add known volume $V$ of liquid\n\n3. Find mass of container + liquid: $m_2$\n\n4. Density: $\\rho = \\frac{m_2 - m_1}{V}$\n\n---\n\n## Key Concepts Summary\n\n### Core Concepts\n\n1. **Mass** = quantity of matter (scalar, kg, invariant)\n\n2. **Weight** = gravitational force on mass (vector, N, location-dependent)\n\n3. **Gravitational field strength**: $g = \\frac{W}{m}$ (N/kg) ≡ acceleration of free fall (m/s²)\n\n4. **Density**: $\\rho = \\frac{m}{V}$; determines whether objects float or sink\n\n5. **Average density** explains why hollow objects (ships, balloons) can float despite being made of dense materials\n\n6. **Immiscible liquids** layer by density: highest at bottom, lowest at top\n\n### Extended Concepts\n\n7. Weight is the **effect of a gravitational field on a mass**: $W = mg$\n\n8. Floating criterion for liquids: a liquid floats on another if $\\rho_1 < \\rho_2$ (provided they do not mix)\n\n---\n\n## Common Misconceptions\n\n### ⚠️ Misconception 1: \"Mass and weight are the same thing\"\n\n**Incorrect:** \"I weigh 60 kg\"\n\n**Correct:** \n- **Mass** = 60 kg (amount of matter, constant)\n- **Weight** = $mg = 60 \\times 10 = 600 \\text{ N}$ on Earth (force, varies with $g$)\n\n**Memory aid:** Mass is *matter*; Weight is *force due to gravity*.\n\n---\n\n### ⚠️ Misconception 2: \"An object has no weight in space\"\n\n**Incorrect:** Astronauts are \"weightless\" because there is no gravity in orbit\n\n**Correct:** \n- Gravity at low Earth orbit is still ~90% of surface value\n- Astronauts experience **apparent weightlessness** because they are in continuous free fall around Earth\n- Their **mass** remains unchanged; their **weight** (gravitational force) is still present\n\n---\n\n### ⚠️ Misconception 3: \"Density depends on the size of the sample\"\n\n**Incorrect:** A large piece of iron is denser than a small piece\n\n**Correct:** Density is an **intensive property**—it depends only on the material, not the amount. Both pieces of pure iron have $\\rho = 7.87 \\text{ g/cm}^3$.\n\n---\n\n### ⚠️ Misconception 4: \"Heavy objects always sink; light objects always float\"\n\n**Incorrect:** A heavy ship sinks; a light coin floats\n\n**Correct:** Floating depends on **average density**, not absolute weight. A massive ship floats because its average density (including air spaces) is less than water's density.\n\n---\n\n### ⚠️ Misconception 5: \"Gravitational field strength $g$ is exactly 10 N/kg everywhere on Earth\"\n\n**Incorrect:** $g$ is constant at 10 N/kg\n\n**Correct:** \n- $g$ varies slightly with latitude, altitude, and local geology (~9.78 to 9.83 N/kg)\n- For IGCSE calculations, we **approximate** $g = 10 \\text{ N/kg}$ unless otherwise specified\n\n---\n\n### ⚠️ Misconception 6: \"Reading a measuring cylinder: look at the top of the meniscus\"\n\n**Incorrect:** Read from the upper curve of the liquid surface\n\n**Correct:** For water and most aqueous solutions, read from the **bottom of the meniscus** at eye level to avoid parallax error.\n\n---\n\n### ⚠️ Misconception 7: \"Beam balances measure weight\"\n\n**Incorrect:** A beam balance gives weight readings\n\n**Correct:** A beam balance **compares masses** by balancing gravitational forces. Since both sides experience the same $g$, the reading is true mass, independent of location.\n\n---\n\n## Worked Examples\n\n### Example 1: Mass vs. Weight on Different Planets\n\n**Question:**\nAn astronaut has a mass of 75 kg. Calculate their weight on:\n(a) Earth ($g = 10 \\text{ N/kg}$)\n(b) Moon ($g = 1.6 \\text{ N/kg}$)\n(c) Jupiter ($g = 22.9 \\text{ N/kg}$)\n\n**Solution:**\nUse $W = mg$\n\n(a) Earth: $W = 75 \\times 10 = \\boxed{750 \\text{ N}}$  \n(b) Moon: $W = 75 \\times 1.6 = \\boxed{120 \\text{ N}}$  \n(c) Jupiter: $W = 75 \\times 22.9 = \\boxed{1717.5 \\text{ N}}$\n\n**Note:** Mass remains 75 kg in all locations.\n\n---\n\n### Example 2: Density Calculation with Unit Conversion\n\n**Question:**\nA metal cube has sides of 2.0 cm and a mass of 62.4 g. Calculate its density in:\n(a) g/cm³\n(b) kg/m³\n\n**Solution:**\n\n**(a) In g/cm³:**\n$$V = (2.0)^3 = 8.0 \\text{ cm}^3$$\n$$\\rho = \\frac{m}{V} = \\frac{62.4}{8.0} = \\boxed{7.8 \\text{ g/cm}^3}$$\n\n**(b) In kg/m³:**\nMethod 1: Convert units first\n$$m = 62.4 \\text{ g} = 0.0624 \\text{ kg}$$\n$$V = 8.0 \\text{ cm}^3 = 8.0 \\times 10^{-6} \\text{ m}^3$$\n$$\\rho = \\frac{0.0624}{8.0 \\times 10^{-6}} = 7800 \\text{ kg/m}^3$$\n\nMethod 2: Use conversion factor\n$$7.8 \\text{ g/cm}^3 \\times 1000 = \\boxed{7800 \\text{ kg/m}^3}$$\n\n**Identification:** This density matches iron/steel ($\\rho \\approx 7.87 \\text{ g/cm}^3$).\n\n---\n\n### Example 3: Floating Criterion (Extended)\n\n**Question:**\nA solid object is placed in three immiscible liquids with densities:\n- Liquid A: 0.85 g/cm³\n- Liquid B: 1.05 g/cm³\n- Liquid C: 1.30 g/cm³\n\nThe object floats in Liquid B and Liquid C, but sinks in Liquid A. What is the possible range for the object's density?\n\n**Solution:**\n- Sinks in A ($\\rho = 0.85$) → $\\rho_{\\text{object}} > 0.85$\n- Floats in B ($\\rho = 1.05$) → $\\rho_{\\text{object}} < 1.05$\n- Floats in C ($\\rho = 1.30$) → $\\rho_{\\text{object}} < 1.30$ (redundant, as <1.05 is stricter)\n\nTherefore: $\\boxed{0.85 \\text{ g/cm}^3 < \\rho_{\\text{object}} < 1.05 \\text{ g/cm}^3}$\n\n---\n\n### Example 4: Density by Displacement\n\n**Question:**\nA measuring cylinder contains 45.0 cm³ of water. When a stone of mass 78.5 g is immersed, the water level rises to 73.5 cm³. Calculate the density of the stone.\n\n**Solution:**\n$$V_{\\text{stone}} = V_2 - V_1 = 73.5 - 45.0 = 28.5 \\text{ cm}^3$$\n$$\\rho = \\frac{m}{V} = \\frac{78.5}{28.5} = \\boxed{2.75 \\text{ g/cm}^3}$$\n\n**Identification:** This density is consistent with aluminium ($\\rho \\approx 2.7 \\text{ g/cm}^3$).\n\n---\n\n## Practice Questions\n\n### Core Level\n\n**1.** Define the term *mass*. State its SI unit.\n\n**2.** A rock has a mass of 2.5 kg. Calculate its weight on Earth ($g = 10 \\text{ N/kg}$).\n\n**3.** Explain why a beam balance gives the same mass reading on Earth and on the Moon, while a spring balance does not.\n\n**4.** Describe how you would determine the density of:\n\n   - (a) a rectangular metal block\n\n   - (b) a small irregular stone that sinks in water\n\n   - (c) a sample of olive oil\n\n**5.** An object has a density of 0.92 g/cm³. Will it float or sink in pure water ($\\rho = 1.00 \\text{ g/cm}^3$)? Explain.\n\n**6.** Convert the following densities:\n\n   - (a) 2.7 g/cm³ to kg/m³\n\n   - (b) 8900 kg/m³ to g/cm³\n\n### Extended Level\n\n**7.** The gravitational field strength on Mars is 3.7 N/kg. An astronaut weighs 740 N on Earth. Calculate:\n\n   - (a) the astronaut's mass\n\n   - (b) the astronaut's weight on Mars\n\n**8.** Two immiscible liquids X ($\\rho = 1.20 \\text{ g/cm}^3$) and Y ($\\rho = 0.85 \\text{ g/cm}^3$) are poured into a measuring cylinder. A solid object of density 1.05 g/cm³ is then added. Describe the final arrangement of the three substances.\n\n**9.** A composite object is made by drilling a 2.0 cm³ hole into a 10.0 cm³ cube of material A ($\\rho_A = 8.0 \\text{ g/cm}^3$) and filling the hole with material B ($\\rho_B = 2.0 \\text{ g/cm}^3$). Calculate the average density of the composite object.\n\n**10.** Explain why the numerical value of $g$ in N/kg is equal to its value in m/s². Use the equations $W = mg$ and $F = ma$ in your explanation.\n\n---\n\n## Laboratory Investigation\n\n### Experiment 3.1: Determining the Density of an Irregular Solid\n\n**Objective:**\nTo determine the density of an irregularly shaped object that sinks in water using the displacement method.\n\n**Apparatus:**\n- Measuring cylinder (100 cm³)\n- Irregular solid (e.g., stone, metal piece)\n- Electronic balance or beam balance\n- String\n- Water\n- Cloth/towel\n\n**Variables:**\n- **Independent:** None (single measurement)\n- **Dependent:** Density $\\rho$\n- **Controlled:** Temperature of water, type of liquid, instrument calibration\n\n**Procedure:**\n\n1. Measure and record the mass $m$ of the dry object using the balance.\n\n2. Fill the measuring cylinder with water to approximately one-third full. Record initial volume $V_1$.\n\n3. Tie the object with string and lower it gently into the water until fully immersed.\n\n4. Record the new volume $V_2$.\n\n5. Remove the object, dry it, and repeat steps 2–4 two more times with different initial volumes.\n\n6. Calculate the average volume: $V_{\\text{avg}} = \\frac{(V_2 - V_1)_1 + (V_2 - V_1)_2 + (V_2 - V_1)_3}{3}$\n\n7. Calculate density: $\\rho = \\frac{m}{V_{\\text{avg}}}$\n\n**Data Table:**\n\n| Trial | $m$ (g) | $V_1$ (cm³) | $V_2$ (cm³) | $V = V_2 - V_1$ (cm³) |\n|:------|:--------|:------------|:------------|:----------------------|\n| 1 | | | | |\n| 2 | | | | |\n| 3 | | | | |\n| **Average** | — | — | — | **$V_{\\text{avg}}$ =** |\n\n**Calculation:**\n$$\\rho = \\frac{m}{V_{\\text{avg}}} \\quad \\text{(g/cm³)} \\quad \\text{or} \\quad \\rho = \\frac{m}{V_{\\text{avg}}} \\times 1000 \\quad \\text{(kg/m³)}$$\n\n**Precautions:**\n- ✓ Read the meniscus at eye level to avoid parallax error\n- ✓ Ensure the object is completely submerged with no air bubbles\n- ✓ Dry the object between trials to prevent water mass affecting balance readings\n- ✓ Check balance for zero error before use\n\n**Analysis Questions:**\n\n1. Why is it important to take multiple readings of volume displacement?\n\n2. If air bubbles cling to the object during immersion, how would this affect the calculated density? (Too high / Too high / Unaffected)\n\n3. Suggest one improvement to increase the accuracy of this experiment.\n\n**Conclusion Template:**\n\"The density of the irregular solid was determined to be ______ g/cm³ (______ kg/m³). This value suggests the material may be ______, based on comparison with standard density tables.\"\n\n---\n\n## Exam-Style Questions\n\n### Paper 1 Style (Multiple Choice)\n\n**1.** Which statement about mass and weight is correct?\n\nA. Mass is a force; weight is a scalar quantity  \nB. Mass changes with location; weight does not  \nC. Mass is measured in newtons; weight in kilograms  \nD. Mass is constant; weight depends on gravitational field strength  \n\n**2.** An object has a mass of 5.0 kg. What is its weight on a planet where $g = 4.0 \\text{ N/kg}$?\n\nA. 1.25 N  \nB. 5.0 N  \nC. 20 N  \nD. 40 N  \n\n**3.** A liquid has a density of 0.85 g/cm³. Which of the following objects will float in this liquid?\n\nA. Object with $\\rho = 0.90 \\text{ g/cm}^3$  \nB. Object with $\\rho = 0.85 \\text{ g/cm}^3$  \nC. Object with $\\rho = 0.80 \\text{ g/cm}^3$  \nD. Object with $\\rho = 1.00 \\text{ g/cm}^3$  \n\n### Paper 3 Style (Structured)\n\n**4.** (a) Define *gravitational field strength*. [1]\n\n(b) The gravitational field strength on the surface of Mercury is 3.7 N/kg.\n\n   (i) Calculate the weight of a 12 kg rock on Mercury. [2]\n\n   (ii) State the mass of the same rock on Earth. [1]\n\n   (iii) Explain why the mass is the same on both planets. [1]\n\n**5.** A student determines the density of a metal sample.\n\n(a) Describe how the student can measure the volume of an irregular metal sample that sinks in water. Include a labelled diagram if helpful. [3]\n\n(b) The student records:\n   - Mass of sample = 89.2 g\n   - Initial water volume = 35.0 cm³\n   - Final water volume = 45.0 cm³\n   \n   Calculate the density of the metal in g/cm³. [2]\n\n(c) Suggest why the student repeated the volume measurement three times. [1]\n\n(d) The calculated density is 8.92 g/cm³. Identify the likely metal using Table 3.2. [1]\n\n---\n\n## Chapter Summary\n\n### Key Points to Remember\n\n✓ **Mass** = quantity of matter (kg, scalar, invariant)  \n✓ **Weight** = gravitational force ($W = mg$, N, vector, location-dependent)  \n✓ **Gravitational field strength**: $g = \\frac{W}{m}$ (N/kg) ≡ acceleration of free fall (m/s²)  \n✓ **Density**: $\\rho = \\frac{m}{V}$; intensive property, material-specific  \n✓ **Floating criterion**: $\\rho_{\\text{object}} < \\rho_{\\text{fluid}}$ → floats  \n✓ **Immiscible liquids** layer by density: highest at bottom  \n✓ **Beam balance** measures mass (location-independent); **spring balance** measures weight (location-dependent)  \n✓ **Displacement method** for irregular solids: $V = V_2 - V_1$  \n✓ **Unit conversion**: $1 \\text{ g/cm}^3 = 1000 \\text{ kg/m}^3$\n\n### Formulae Sheet\n\n| Quantity | Formula | Variables |\n|:---------|:--------|:----------|\n| Weight | $W = mg$ | $W$=weight (N), $m$=mass (kg), $g$=field strength (N/kg) |\n| Gravitational field strength | $g = \\frac{W}{m}$ | Same as above |\n| Density | $\\rho = \\frac{m}{V}$ | $\\rho$=density, $m$=mass, $V$=volume |\n| Volume by displacement | $V = V_2 - V_1$ | $V_1$=initial volume, $V_2$=final volume |\n\n---\n\n## Further Resources\n\n### Recommended Reading\n- Cambridge IGCSE Physics Coursebook, Chapter 3\n- Practical Work in Physics: Measurement of Mass, Weight and Density\n\n### Online Resources\n- PhET Interactive Simulations: Masses & Springs, Density\n- BBC Bitesize: Mass, Weight and Density\n\n### Video Resources\n- Demonstration: Measuring density of irregular objects\n- Animation: Why ships float—average density explained\n\n---\n\n## Glossary\n\n| Term | Definition |\n|:-----|:-----------|\n| **Average density** | Total mass divided by total volume of a composite object |\n| **Beam balance** | Instrument that compares masses using gravitational forces; gives location-independent readings |\n| **Density ($\\rho$)** | Mass per unit volume; $\\rho = m/V$ |\n| **Displacement method** | Technique to find volume of irregular solids by measuring water level change |\n| **Gravitational field strength ($g$)** | Force per unit mass; $g = W/m$; numerically equal to acceleration of free fall |\n| **Immiscible** | Liquids that do not mix when combined |\n| **Intensive property** | Property independent of sample size (e.g., density, temperature) |\n| **Mass** | Measure of quantity of matter; scalar; SI unit: kilogram (kg) |\n| **Meniscus** | Curved surface of a liquid in a container; read from bottom for water |\n| **Spring balance** | Instrument that measures weight via spring extension; reading depends on local $g$ |\n| **Weight** | Gravitational force on a mass; vector; SI unit: newton (N); $W = mg$ |\n\n---\n\n*End of Chapter*\n\n",
    "supporting": [
      "03-mass-weight-density_files\\figure-docx"
    ],
    "filters": []
  }
}