<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Sugeng Riyanto, M.Sc.">
<meta name="dcterms.date" content="2026-01-01">

<title>18&nbsp; Light: Reflection and Refraction – Cambridge IGCSE Physics 0625: Last-Minute Revision Guide</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapters/16-em-spectrum.html" rel="next">
<link href="../chapters/14-wave-properties.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-845c23b38eaddc0f92fda52bfe77a8c8.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-932514a4c912dae26ceaa3c5ace84409.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/01-measurement.html">Core Content</a></li><li class="breadcrumb-item"><a href="../chapters/15-light-reflection-refraction.html"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Light: Reflection and Refraction</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Cambridge IGCSE Physics 0625: Last-Minute Revision Guide</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Cambridge IGCSE Physics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../syllabus-map.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Syllabus Mapping</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Preface</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Core Content</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/01-measurement.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Measurement of Physical Quantities</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/02-motion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Motion</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/03-mass-weight-density.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Mass, Weight and Density</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/04-forces.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Forces</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/05-moments-equilibrium.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Moments and Equilibrium</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/06-momentum.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Momentum</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/07-energy-stores.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Energy Stores</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/08-work-power.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Work and Power</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/09-pressure.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Pressure</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/10-kinetic-particle-model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Kinetic Particle Model of Matter</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/11-thermal-properties.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Thermal Properties</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/12-phase-changes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Phase Changes</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/13-thermal-transfer.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Thermal Transfer</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/14-wave-properties.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">General Properties of Waves</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/15-light-reflection-refraction.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Light: Reflection and Refraction</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/16-em-spectrum.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Electromagnetic Spectrum</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/17-sound.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Sound</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/18-magnetism.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Simple Phenomena of Magnetism</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/19-electric-charge-circuits.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Electric Charge and Circuits</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/20-electrical-quantities.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Electrical Quantities</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/21-electromagnetic-effects.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Electromagnetic Effects</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/22-nuclear-physics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Nuclear Physics</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/23-space-physics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Space Physics</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Supporting Materials</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../back-matter/practical-skills.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Practical Skills</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../back-matter/maths-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Mathematical Data and Constants</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../back-matter/exam-technique.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Common Question Types</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../back-matter/formula-sheet.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Formula Sheet</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../back-matter/bibliography.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Bibliography and References</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../back-matter/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Cambridge IGCSE Physics Reference Guide</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul class="collapse">
  <li><a href="#learning-objectives" id="toc-learning-objectives" class="nav-link active" data-scroll-target="#learning-objectives"><span class="header-section-number">18.1</span> Learning Objectives</a></li>
  <li><a href="#introduction-to-light" id="toc-introduction-to-light" class="nav-link" data-scroll-target="#introduction-to-light"><span class="header-section-number">18.2</span> Introduction to Light</a></li>
  <li><a href="#reflection-of-light" id="toc-reflection-of-light" class="nav-link" data-scroll-target="#reflection-of-light"><span class="header-section-number">18.3</span> Reflection of Light</a></li>
  <li><a href="#refraction-of-light" id="toc-refraction-of-light" class="nav-link" data-scroll-target="#refraction-of-light"><span class="header-section-number">18.4</span> Refraction of Light</a></li>
  <li><a href="#total-internal-reflection" id="toc-total-internal-reflection" class="nav-link" data-scroll-target="#total-internal-reflection"><span class="header-section-number">18.5</span> Total Internal Reflection</a></li>
  <li><a href="#key-concepts-summary" id="toc-key-concepts-summary" class="nav-link" data-scroll-target="#key-concepts-summary"><span class="header-section-number">18.6</span> Key Concepts Summary</a></li>
  <li><a href="#common-misconceptions" id="toc-common-misconceptions" class="nav-link" data-scroll-target="#common-misconceptions"><span class="header-section-number">18.7</span> Common Misconceptions</a></li>
  <li><a href="#worked-examples" id="toc-worked-examples" class="nav-link" data-scroll-target="#worked-examples"><span class="header-section-number">18.8</span> Worked Examples</a></li>
  <li><a href="#practice-questions" id="toc-practice-questions" class="nav-link" data-scroll-target="#practice-questions"><span class="header-section-number">18.9</span> Practice Questions</a></li>
  <li><a href="#laboratory-investigation" id="toc-laboratory-investigation" class="nav-link" data-scroll-target="#laboratory-investigation"><span class="header-section-number">18.10</span> Laboratory Investigation</a></li>
  <li><a href="#exam-style-questions" id="toc-exam-style-questions" class="nav-link" data-scroll-target="#exam-style-questions"><span class="header-section-number">18.11</span> Exam-Style Questions</a></li>
  <li><a href="#chapter-summary" id="toc-chapter-summary" class="nav-link" data-scroll-target="#chapter-summary"><span class="header-section-number">18.12</span> Chapter Summary</a></li>
  <li><a href="#further-resources" id="toc-further-resources" class="nav-link" data-scroll-target="#further-resources"><span class="header-section-number">18.13</span> Further Resources</a></li>
  <li><a href="#glossary" id="toc-glossary" class="nav-link" data-scroll-target="#glossary"><span class="header-section-number">18.14</span> Glossary</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/01-measurement.html">Core Content</a></li><li class="breadcrumb-item"><a href="../chapters/15-light-reflection-refraction.html"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Light: Reflection and Refraction</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Light: Reflection and Refraction</span></h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Sugeng Riyanto, M.Sc. </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">January 1, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="learning-objectives" class="level2" data-number="18.1">
<h2 data-number="18.1" class="anchored" data-anchor-id="learning-objectives"><span class="header-section-number">18.1</span> Learning Objectives</h2>
<p>By the end of this chapter, you will be able to:</p>
<p><strong>Core Content (3.2.1 Reflection of Light):</strong></p>
<ul>
<li><p>Define and use the terms normal, angle of incidence and angle of reflection</p></li>
<li><p>Describe the formation of an optical image by a plane mirror, and give the characteristics of the image</p></li>
<li><p>State that for reflection, the angle of incidence is equal to the angle of reflection; recall and use this relationship</p></li>
</ul>
<p><strong>Core Content (3.2.2 Refraction of Light):</strong></p>
<ul>
<li><p>Define and use the terms normal, angle of incidence and angle of refraction</p></li>
<li><p>Describe an experiment to show refraction of light by transparent blocks of different shapes</p></li>
<li><p>Describe the passage of light through a transparent material (limited to the boundaries between two mediums only)</p></li>
<li><p>State the meaning of critical angle</p></li>
<li><p>Describe internal reflection and total internal reflection using both experimental and everyday examples</p></li>
</ul>
<p><strong>Supplement (Extended):</strong></p>
<ul>
<li><p>Use simple constructions, measurements and calculations for reflection by plane mirrors</p></li>
<li><p>Define refractive index, n, as the ratio of the speeds of a wave in two different regions</p></li>
<li><p>Recall and use the equation <span class="math inline">\(n = \frac{\sin i}{\sin r}\)</span></p></li>
<li><p>Recall and use the equation <span class="math inline">\(n = \frac{1}{\sin c}\)</span></p></li>
<li><p>Describe the use of optical fibres, particularly in telecommunications</p></li>
</ul>
<hr>
</section>
<section id="introduction-to-light" class="level2" data-number="18.2">
<h2 data-number="18.2" class="anchored" data-anchor-id="introduction-to-light"><span class="header-section-number">18.2</span> Introduction to Light</h2>
<section id="what-is-light" class="level3" data-number="18.2.1">
<h3 data-number="18.2.1" class="anchored" data-anchor-id="what-is-light"><span class="header-section-number">18.2.1</span> What Is Light?</h3>
<p>Light is a form of electromagnetic radiation that is visible to the human eye. It travels in straight lines and can be reflected, refracted, and dispersed.</p>
<p><strong>Key properties of light:</strong></p>
<ul>
<li><p>Light travels at approximately <span class="math inline">\(3.0 \times 10^8\)</span> m/s in a vacuum</p></li>
<li><p>Light travels in straight lines (rectilinear propagation)</p></li>
<li><p>Light can be reflected, refracted, absorbed, or transmitted</p></li>
<li><p>Light exhibits both wave and particle properties (beyond IGCSE scope)</p></li>
</ul>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Key Concept:</strong> We see objects because light from them enters our eyes. Luminous objects (e.g., the Sun, a lamp) emit their own light. Non-luminous objects (e.g., a book, a wall) are visible because they reflect light from a luminous source into our eyes.</p>
</div>
</div>
</section>
<section id="representing-light-rays-and-beams" class="level3" data-number="18.2.2">
<h3 data-number="18.2.2" class="anchored" data-anchor-id="representing-light-rays-and-beams"><span class="header-section-number">18.2.2</span> Representing Light: Rays and Beams</h3>
<p>In physics, we use <strong>light rays</strong> to represent the path of light:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 29%">
<col style="width: 56%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Term</th>
<th style="text-align: left;">Definition</th>
<th style="text-align: left;">Diagram Representation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Ray</strong></td>
<td style="text-align: left;">A straight line with an arrow indicating the direction of light travel</td>
<td style="text-align: left;">Single line with arrow</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Beam</strong></td>
<td style="text-align: left;">A bundle of parallel, convergent, or divergent rays</td>
<td style="text-align: left;">Multiple parallel/convergent/divergent lines</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Parallel beam</strong></td>
<td style="text-align: left;">Rays that are parallel to each other</td>
<td style="text-align: left;">Parallel lines with arrows</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Convergent beam</strong></td>
<td style="text-align: left;">Rays that meet at a point</td>
<td style="text-align: left;">Lines converging to a point</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Divergent beam</strong></td>
<td style="text-align: left;">Rays that spread out from a point</td>
<td style="text-align: left;">Lines spreading from a point</td>
</tr>
</tbody>
</table>
<hr>
</section>
</section>
<section id="reflection-of-light" class="level2" data-number="18.3">
<h2 data-number="18.3" class="anchored" data-anchor-id="reflection-of-light"><span class="header-section-number">18.3</span> Reflection of Light</h2>
<section id="the-law-of-reflection" class="level3" data-number="18.3.1">
<h3 data-number="18.3.1" class="anchored" data-anchor-id="the-law-of-reflection"><span class="header-section-number">18.3.1</span> The Law of Reflection</h3>
<p>When light strikes a smooth, polished surface (e.g., a plane mirror), it is reflected in a predictable manner.</p>
<p><strong>Key terms for reflection:</strong></p>
<ul>
<li><p><strong>Incident ray</strong>: The ray of light that strikes the reflecting surface</p></li>
<li><p><strong>Reflected ray</strong>: The ray of light that bounces off the reflecting surface</p></li>
<li><p><strong>Point of incidence</strong>: The point where the incident ray strikes the surface</p></li>
<li><p><strong>Normal</strong>: An imaginary line perpendicular to the reflecting surface at the point of incidence</p></li>
<li><p><strong>Angle of incidence (<span class="math inline">\(i\)</span>)</strong>: The angle between the incident ray and the normal</p></li>
<li><p><strong>Angle of reflection (<span class="math inline">\(r\)</span>)</strong>: The angle between the reflected ray and the normal</p></li>
</ul>
<p><strong>The Law of Reflection states:</strong></p>
<ol type="1">
<li><p>The angle of incidence is equal to the angle of reflection: <span class="math inline">\(i = r\)</span></p></li>
<li><p>The incident ray, reflected ray, and normal all lie in the same plane</p></li>
</ol>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Important:</strong> Angles are always measured from the <strong>normal</strong>, not from the surface itself.</p>
</div>
</div>
</section>
<section id="images-formed-by-plane-mirrors" class="level3" data-number="18.3.2">
<h3 data-number="18.3.2" class="anchored" data-anchor-id="images-formed-by-plane-mirrors"><span class="header-section-number">18.3.2</span> Images Formed by Plane Mirrors</h3>
<p>When you look into a plane mirror, you see an <strong>image</strong> of yourself. This image has specific characteristics:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 55%">
<col style="width: 44%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Characteristic</th>
<th style="text-align: left;">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Same size</strong></td>
<td style="text-align: left;">The image is the same size as the object</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Same distance</strong></td>
<td style="text-align: left;">The image is as far behind the mirror as the object is in front</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Virtual</strong></td>
<td style="text-align: left;">The image cannot be captured on a screen; light rays do not actually meet at the image position</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Upright</strong></td>
<td style="text-align: left;">The image is the right way up (not inverted)</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Laterally inverted</strong></td>
<td style="text-align: left;">Left and right are swapped (e.g., text appears reversed)</td>
</tr>
</tbody>
</table>
</section>
<section id="ray-diagrams-for-plane-mirrors" class="level3" data-number="18.3.3">
<h3 data-number="18.3.3" class="anchored" data-anchor-id="ray-diagrams-for-plane-mirrors"><span class="header-section-number">18.3.3</span> Ray Diagrams for Plane Mirrors</h3>
<p>To locate the position of an image formed by a plane mirror:</p>
<p><strong>Step 1:</strong> Draw the mirror as a straight line with shading on the back (silvered side).</p>
<p><strong>Step 2:</strong> Mark the object position in front of the mirror.</p>
<p><strong>Step 3:</strong> Draw the image behind the mirror at the same distance as the object is in front.</p>
<p><strong>Step 4:</strong> From the top of the image, draw two rays to the eye (dotted lines behind the mirror, solid lines in front).</p>
<p><strong>Step 5:</strong> Draw the incident rays from the object to the mirror, ensuring <span class="math inline">\(i = r\)</span> at each point of incidence.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Key Insight:</strong> The image is virtual because the rays only <strong>appear</strong> to come from behind the mirror. In reality, the light rays reflect off the mirror and enter the eye.</p>
</div>
</div>
</section>
<section id="applications-of-plane-mirrors" class="level3" data-number="18.3.4">
<h3 data-number="18.3.4" class="anchored" data-anchor-id="applications-of-plane-mirrors"><span class="header-section-number">18.3.4</span> Applications of Plane Mirrors</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Application</th>
<th style="text-align: left;">Explanation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Periscope</strong></td>
<td style="text-align: left;">Two plane mirrors at 45° allow viewing over obstacles (e.g., in submarines)</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Rear-view mirrors</strong></td>
<td style="text-align: left;">Drivers use plane or slightly curved mirrors to see behind vehicles</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Optical instruments</strong></td>
<td style="text-align: left;">Mirrors redirect light in telescopes, microscopes, and cameras</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Vision testing</strong></td>
<td style="text-align: left;">Mirrors extend the apparent distance of eye charts in small rooms</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Blind corner mirrors</strong></td>
<td style="text-align: left;">Curved mirrors help drivers see around corners in shops or on roads</td>
</tr>
</tbody>
</table>
<hr>
</section>
</section>
<section id="refraction-of-light" class="level2" data-number="18.4">
<h2 data-number="18.4" class="anchored" data-anchor-id="refraction-of-light"><span class="header-section-number">18.4</span> Refraction of Light</h2>
<section id="what-is-refraction" class="level3" data-number="18.4.1">
<h3 data-number="18.4.1" class="anchored" data-anchor-id="what-is-refraction"><span class="header-section-number">18.4.1</span> What Is Refraction?</h3>
<p><strong>Refraction</strong> is the bending of light as it passes from one transparent medium to another with a different optical density.</p>
<p><strong>Why does refraction occur?</strong></p>
<ul>
<li><p>Light travels at different speeds in different media</p></li>
<li><p>When light enters a denser medium (e.g., air → glass), it <strong>slows down</strong> and bends <strong>towards the normal</strong></p></li>
<li><p>When light enters a less dense medium (e.g., glass → air), it <strong>speeds up</strong> and bends <strong>away from the normal</strong></p></li>
</ul>
<p><strong>Key terms for refraction:</strong></p>
<ul>
<li><p><strong>Incident ray</strong>: The ray approaching the boundary between two media</p></li>
<li><p><strong>Refracted ray</strong>: The ray that has passed into the second medium and changed direction</p></li>
<li><p><strong>Normal</strong>: An imaginary line perpendicular to the boundary at the point of incidence</p></li>
<li><p><strong>Angle of incidence (<span class="math inline">\(i\)</span>)</strong>: The angle between the incident ray and the normal</p></li>
<li><p><strong>Angle of refraction (<span class="math inline">\(r\)</span>)</strong>: The angle between the refracted ray and the normal</p></li>
</ul>
</section>
<section id="snells-law-and-refractive-index" class="level3" data-number="18.4.2">
<h3 data-number="18.4.2" class="anchored" data-anchor-id="snells-law-and-refractive-index"><span class="header-section-number">18.4.2</span> Snell’s Law and Refractive Index</h3>
<p>For light passing from air (or vacuum) into another medium:</p>
<p><span class="math display">\[n = \frac{\sin i}{\sin r}\]</span></p>
<p>Where: - <span class="math inline">\(n\)</span> = refractive index of the medium (no unit) - <span class="math inline">\(i\)</span> = angle of incidence in air/vacuum - <span class="math inline">\(r\)</span> = angle of refraction in the medium</p>
<p><strong>Refractive index</strong> can also be defined as:</p>
<p><span class="math display">\[n = \frac{\text{speed of light in vacuum}}{\text{speed of light in medium}} = \frac{c}{v}\]</span></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Medium</th>
<th style="text-align: left;">Refractive Index (<span class="math inline">\(n\)</span>)</th>
<th style="text-align: left;">Speed of Light (<span class="math inline">\(\times 10^8\)</span> m/s)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Vacuum</td>
<td style="text-align: left;">1.00 (exact)</td>
<td style="text-align: left;">3.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">Air</td>
<td style="text-align: left;">≈ 1.00</td>
<td style="text-align: left;">≈ 3.00</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Water</td>
<td style="text-align: left;">1.33</td>
<td style="text-align: left;">2.25</td>
</tr>
<tr class="even">
<td style="text-align: left;">Glass</td>
<td style="text-align: left;">≈ 1.50</td>
<td style="text-align: left;">≈ 2.00</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Diamond</td>
<td style="text-align: left;">2.42</td>
<td style="text-align: left;">1.24</td>
</tr>
</tbody>
</table>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Key Insight:</strong> A higher refractive index means light travels <strong>slower</strong> in that medium and bends <strong>more</strong> towards the normal when entering from air.</p>
</div>
</div>
</section>
<section id="apparent-depth-and-real-depth" class="level3" data-number="18.4.3">
<h3 data-number="18.4.3" class="anchored" data-anchor-id="apparent-depth-and-real-depth"><span class="header-section-number">18.4.3</span> Apparent Depth and Real Depth</h3>
<p>When viewing an object underwater, it appears <strong>shallower</strong> than it actually is due to refraction.</p>
<p><strong>Relationship:</strong> <span class="math display">\[n = \frac{\text{real depth}}{\text{apparent depth}}\]</span></p>
<p><strong>Example:</strong> A coin at the bottom of a pool appears closer to the surface than it really is. Light rays from the coin refract away from the normal as they leave the water, making the coin appear at a shallower position.</p>
<hr>
</section>
</section>
<section id="total-internal-reflection" class="level2" data-number="18.5">
<h2 data-number="18.5" class="anchored" data-anchor-id="total-internal-reflection"><span class="header-section-number">18.5</span> Total Internal Reflection</h2>
<section id="what-is-the-critical-angle" class="level3" data-number="18.5.1">
<h3 data-number="18.5.1" class="anchored" data-anchor-id="what-is-the-critical-angle"><span class="header-section-number">18.5.1</span> What Is the Critical Angle?</h3>
<p>When light travels from a denser medium to a less dense medium (e.g., glass → air):</p>
<ul>
<li><p>As the angle of incidence increases, the angle of refraction increases more rapidly</p></li>
<li><p>At a certain angle of incidence, the angle of refraction becomes <strong>90°</strong> (the refracted ray travels along the boundary)</p></li>
<li><p>This specific angle of incidence is called the <strong>critical angle (<span class="math inline">\(c\)</span>)</strong></p></li>
</ul>
<p><strong>Definition:</strong> The critical angle is the angle of incidence in the denser medium for which the angle of refraction in the less dense medium is 90°.</p>
</section>
<section id="total-internal-reflection-1" class="level3" data-number="18.5.2">
<h3 data-number="18.5.2" class="anchored" data-anchor-id="total-internal-reflection-1"><span class="header-section-number">18.5.2</span> Total Internal Reflection</h3>
<p>When the angle of incidence in the denser medium <strong>exceeds</strong> the critical angle:</p>
<ul>
<li><p><strong>No refraction occurs</strong></p></li>
<li><p><strong>All the light is reflected back</strong> into the denser medium</p></li>
<li><p>This phenomenon is called <strong>total internal reflection</strong></p></li>
</ul>
<p><strong>Conditions for total internal reflection:</strong></p>
<ol type="1">
<li><p>Light must travel from a <strong>denser medium to a less dense medium</strong></p></li>
<li><p>The angle of incidence must be <strong>greater than the critical angle</strong></p></li>
</ol>
</section>
<section id="calculating-critical-angle" class="level3" data-number="18.5.3">
<h3 data-number="18.5.3" class="anchored" data-anchor-id="calculating-critical-angle"><span class="header-section-number">18.5.3</span> Calculating Critical Angle</h3>
<p>For light travelling from a medium of refractive index <span class="math inline">\(n\)</span> to air:</p>
<p><span class="math display">\[n = \frac{1}{\sin c} \quad \text{or} \quad \sin c = \frac{1}{n}\]</span></p>
<p><strong>Example:</strong> For glass with <span class="math inline">\(n = 1.5\)</span>: <span class="math display">\[\sin c = \frac{1}{1.5} = 0.667 \quad \Rightarrow \quad c = \sin^{-1}(0.667) \approx 42^\circ\]</span></p>
</section>
<section id="applications-of-total-internal-reflection" class="level3" data-number="18.5.4">
<h3 data-number="18.5.4" class="anchored" data-anchor-id="applications-of-total-internal-reflection"><span class="header-section-number">18.5.4</span> Applications of Total Internal Reflection</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Application</th>
<th style="text-align: left;">Explanation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Optical fibres</strong></td>
<td style="text-align: left;">Light is trapped inside a glass/plastic core by total internal reflection; used for high-speed data transmission in telecommunications</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Prisms in binoculars</strong></td>
<td style="text-align: left;">Right-angled prisms reflect light by total internal reflection, producing upright images without silvered surfaces</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Periscopes</strong></td>
<td style="text-align: left;">Prisms can replace mirrors for clearer, more durable image reflection</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Endoscopes</strong></td>
<td style="text-align: left;">Flexible optical fibres allow doctors to see inside the body without invasive surgery</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Reflectors on bicycles</strong></td>
<td style="text-align: left;">Prismatic reflectors return light to its source using total internal reflection</td>
</tr>
</tbody>
</table>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Important:</strong> Total internal reflection is <strong>100% efficient</strong> (no light is lost), unlike reflection from a silvered mirror which absorbs some light.</p>
</div>
</div>
<hr>
</section>
</section>
<section id="key-concepts-summary" class="level2" data-number="18.6">
<h2 data-number="18.6" class="anchored" data-anchor-id="key-concepts-summary"><span class="header-section-number">18.6</span> Key Concepts Summary</h2>
<section id="core-concepts" class="level3" data-number="18.6.1">
<h3 data-number="18.6.1" class="anchored" data-anchor-id="core-concepts"><span class="header-section-number">18.6.1</span> Core Concepts</h3>
<ol type="1">
<li><p><strong>Reflection</strong>: Light bounces off a surface; <span class="math inline">\(i = r\)</span>; incident ray, reflected ray, and normal lie in same plane</p></li>
<li><p><strong>Plane mirror image</strong>: Same size, same distance behind mirror, virtual, upright, laterally inverted</p></li>
<li><p><strong>Refraction</strong>: Light bends when passing between media of different optical density due to change in speed</p></li>
<li><p><strong>Snell’s Law</strong>: <span class="math inline">\(n = \frac{\sin i}{\sin r}\)</span> for light entering from air/vacuum</p></li>
<li><p><strong>Refractive index</strong>: <span class="math inline">\(n = \frac{c}{v}\)</span>; higher <span class="math inline">\(n\)</span> means slower light speed and greater bending</p></li>
<li><p><strong>Critical angle</strong>: Angle of incidence in denser medium for which refraction angle = 90°</p></li>
<li><p><strong>Total internal reflection</strong>: Complete reflection when <span class="math inline">\(i &gt; c\)</span> and light travels denser → less dense medium</p></li>
</ol>
</section>
<section id="extended-concepts" class="level3" data-number="18.6.2">
<h3 data-number="18.6.2" class="anchored" data-anchor-id="extended-concepts"><span class="header-section-number">18.6.2</span> Extended Concepts</h3>
<ol start="8" type="1">
<li><p><strong>Apparent depth</strong>: <span class="math inline">\(n = \frac{\text{real depth}}{\text{apparent depth}}\)</span>; objects underwater appear shallower</p></li>
<li><p><strong>Optical fibres</strong>: Use total internal reflection to transmit light/data over long distances with minimal loss</p></li>
<li><p><strong>Ray diagram constructions</strong>: Using geometry and <span class="math inline">\(i = r\)</span> to locate images and trace light paths</p></li>
</ol>
<hr>
</section>
</section>
<section id="common-misconceptions" class="level2" data-number="18.7">
<h2 data-number="18.7" class="anchored" data-anchor-id="common-misconceptions"><span class="header-section-number">18.7</span> Common Misconceptions</h2>
<section id="misconception-1-the-angle-of-incidence-is-measured-from-the-mirror-surface" class="level3" data-number="18.7.1">
<h3 data-number="18.7.1" class="anchored" data-anchor-id="misconception-1-the-angle-of-incidence-is-measured-from-the-mirror-surface"><span class="header-section-number">18.7.1</span> ⚠️ Misconception 1: “The angle of incidence is measured from the mirror surface”</h3>
<p><strong>Incorrect</strong>: “Angle of incidence is the angle between the incident ray and the mirror”</p>
<p><strong>Correct</strong>: - Angles of incidence and reflection are <strong>always measured from the normal</strong> (perpendicular to the surface)</p>
<ul>
<li><p>Measuring from the surface gives the complement of the correct angle</p></li>
<li><p>This error leads to incorrect ray diagrams and calculations</p></li>
</ul>
<hr>
</section>
<section id="misconception-2-virtual-images-can-be-captured-on-a-screen" class="level3" data-number="18.7.2">
<h3 data-number="18.7.2" class="anchored" data-anchor-id="misconception-2-virtual-images-can-be-captured-on-a-screen"><span class="header-section-number">18.7.2</span> ⚠️ Misconception 2: “Virtual images can be captured on a screen”</h3>
<p><strong>Incorrect</strong>: “A mirror image can be projected onto a wall”</p>
<p><strong>Correct</strong>: - <strong>Virtual images</strong> are formed where light rays <strong>appear</strong> to come from, but do not actually meet</p>
<ul>
<li><p>Only <strong>real images</strong> (where rays actually converge) can be captured on a screen</p></li>
<li><p>Plane mirrors always produce virtual images</p></li>
</ul>
<hr>
</section>
<section id="misconception-3-refraction-changes-the-frequency-of-light" class="level3" data-number="18.7.3">
<h3 data-number="18.7.3" class="anchored" data-anchor-id="misconception-3-refraction-changes-the-frequency-of-light"><span class="header-section-number">18.7.3</span> ⚠️ Misconception 3: “Refraction changes the frequency of light”</h3>
<p><strong>Incorrect</strong>: “When light enters glass, its frequency decreases”</p>
<p><strong>Correct</strong>: - <strong>Frequency remains constant</strong> during refraction</p>
<ul>
<li><p>Speed and wavelength change, but frequency (determined by the source) does not</p></li>
<li><p>This is why the colour of light does not change when it refracts</p></li>
</ul>
<hr>
</section>
<section id="misconception-4-total-internal-reflection-can-occur-when-light-travels-from-air-to-glass" class="level3" data-number="18.7.4">
<h3 data-number="18.7.4" class="anchored" data-anchor-id="misconception-4-total-internal-reflection-can-occur-when-light-travels-from-air-to-glass"><span class="header-section-number">18.7.4</span> ⚠️ Misconception 4: “Total internal reflection can occur when light travels from air to glass”</h3>
<p><strong>Incorrect</strong>: “Light can undergo total internal reflection entering a denser medium”</p>
<p><strong>Correct</strong>: - Total internal reflection <strong>only occurs</strong> when light travels from a <strong>denser to a less dense medium</strong></p>
<ul>
<li><p>When entering a denser medium (air → glass), light always refracts (bends towards normal)</p></li>
<li><p>The critical angle concept only applies for denser → less dense transitions</p></li>
</ul>
<hr>
</section>
<section id="misconception-5-a-higher-refractive-index-means-light-travels-faster" class="level3" data-number="18.7.5">
<h3 data-number="18.7.5" class="anchored" data-anchor-id="misconception-5-a-higher-refractive-index-means-light-travels-faster"><span class="header-section-number">18.7.5</span> ⚠️ Misconception 5: “A higher refractive index means light travels faster”</h3>
<p><strong>Incorrect</strong>: “Diamond has a high refractive index, so light travels fast in it”</p>
<p><strong>Correct</strong>: - Refractive index <span class="math inline">\(n = \frac{c}{v}\)</span>; higher <span class="math inline">\(n\)</span> means <strong>slower</strong> light speed in the medium</p>
<ul>
<li><p>Diamond (<span class="math inline">\(n = 2.42\)</span>) slows light to about <span class="math inline">\(1.24 \times 10^8\)</span> m/s, much slower than in air</p></li>
<li><p>Greater slowing causes greater bending towards the normal</p></li>
</ul>
<hr>
</section>
<section id="misconception-6-lateral-inversion-means-the-image-is-upside-down" class="level3" data-number="18.7.6">
<h3 data-number="18.7.6" class="anchored" data-anchor-id="misconception-6-lateral-inversion-means-the-image-is-upside-down"><span class="header-section-number">18.7.6</span> ⚠️ Misconception 6: “Lateral inversion means the image is upside down”</h3>
<p><strong>Incorrect</strong>: “A mirror turns your image upside down”</p>
<p><strong>Correct</strong>: - <strong>Lateral inversion</strong> means left and right are swapped, not top and bottom</p>
<ul>
<li><p>Your right hand appears as the left hand in the mirror image</p></li>
<li><p>The image remains upright; only the horizontal orientation is reversed</p></li>
</ul>
<hr>
</section>
<section id="misconception-7-critical-angle-is-the-same-for-all-materials" class="level3" data-number="18.7.7">
<h3 data-number="18.7.7" class="anchored" data-anchor-id="misconception-7-critical-angle-is-the-same-for-all-materials"><span class="header-section-number">18.7.7</span> ⚠️ Misconception 7: “Critical angle is the same for all materials”</h3>
<p><strong>Incorrect</strong>: “All glass has a critical angle of 42°”</p>
<p><strong>Correct</strong>: - Critical angle depends on refractive index: <span class="math inline">\(\sin c = \frac{1}{n}\)</span></p>
<ul>
<li><p>Different types of glass have different <span class="math inline">\(n\)</span> values (1.48–1.96), so critical angles vary (~32°–43°)</p></li>
<li><p>Water (<span class="math inline">\(n = 1.33\)</span>) has <span class="math inline">\(c \approx 49^\circ\)</span>; diamond (<span class="math inline">\(n = 2.42\)</span>) has <span class="math inline">\(c \approx 24^\circ\)</span></p></li>
</ul>
<hr>
</section>
</section>
<section id="worked-examples" class="level2" data-number="18.8">
<h2 data-number="18.8" class="anchored" data-anchor-id="worked-examples"><span class="header-section-number">18.8</span> Worked Examples</h2>
<section id="example-1-law-of-reflection-calculation" class="level3" data-number="18.8.1">
<h3 data-number="18.8.1" class="anchored" data-anchor-id="example-1-law-of-reflection-calculation"><span class="header-section-number">18.8.1</span> Example 1: Law of Reflection Calculation</h3>
<p><strong>Question:</strong> A ray of light strikes a plane mirror at an angle of 35° to the normal. (a) What is the angle of reflection? (b) What is the angle between the incident ray and the reflected ray?</p>
<p><strong>Solution:</strong></p>
<p><strong>(a) Angle of reflection:</strong> By the law of reflection: <span class="math inline">\(r = i = \boxed{35^\circ}\)</span></p>
<p><strong>(b) Angle between incident and reflected rays:</strong> Angle = <span class="math inline">\(i + r = 35^\circ + 35^\circ = \boxed{70^\circ}\)</span></p>
<hr>
</section>
<section id="example-2-plane-mirror-image-distance" class="level3" data-number="18.8.2">
<h3 data-number="18.8.2" class="anchored" data-anchor-id="example-2-plane-mirror-image-distance"><span class="header-section-number">18.8.2</span> Example 2: Plane Mirror Image Distance</h3>
<p><strong>Question:</strong> A person stands 2.5 m in front of a plane mirror. (a) How far is the image from the mirror? (b) How far is the person from their image? (c) If the person moves 0.5 m closer to the mirror, what is the new distance between the person and their image?</p>
<p><strong>Solution:</strong></p>
<p><strong>(a) Image distance from mirror:</strong> Image distance = object distance = <span class="math inline">\(\boxed{2.5 \text{ m}}\)</span></p>
<p><strong>(b) Person-to-image distance:</strong> Distance = <span class="math inline">\(2.5 + 2.5 = \boxed{5.0 \text{ m}}\)</span></p>
<p><strong>(c) New distance after moving closer:</strong> New object distance = <span class="math inline">\(2.5 - 0.5 = 2.0 \text{ m}\)</span> New image distance = <span class="math inline">\(2.0 \text{ m}\)</span> New person-to-image distance = <span class="math inline">\(2.0 + 2.0 = \boxed{4.0 \text{ m}}\)</span></p>
<hr>
</section>
<section id="example-3-snells-law-calculation" class="level3" data-number="18.8.3">
<h3 data-number="18.8.3" class="anchored" data-anchor-id="example-3-snells-law-calculation"><span class="header-section-number">18.8.3</span> Example 3: Snell’s Law Calculation</h3>
<p><strong>Question:</strong> Light travels from air into glass (<span class="math inline">\(n = 1.50\)</span>) at an angle of incidence of 40°. Calculate the angle of refraction.</p>
<p><strong>Solution:</strong></p>
<p><strong>Step 1:</strong> Write Snell’s Law: <span class="math display">\[n = \frac{\sin i}{\sin r}\]</span></p>
<p><strong>Step 2:</strong> Rearrange for <span class="math inline">\(\sin r\)</span>: <span class="math display">\[\sin r = \frac{\sin i}{n} = \frac{\sin 40^\circ}{1.50}\]</span></p>
<p><strong>Step 3:</strong> Calculate: <span class="math display">\[\sin r = \frac{0.643}{1.50} = 0.429\]</span> <span class="math display">\[r = \sin^{-1}(0.429) = \boxed{25.4^\circ}\]</span></p>
<p><strong>Interpretation:</strong> The ray bends towards the normal as expected when entering a denser medium.</p>
<hr>
</section>
<section id="example-4-critical-angle-and-total-internal-reflection" class="level3" data-number="18.8.4">
<h3 data-number="18.8.4" class="anchored" data-anchor-id="example-4-critical-angle-and-total-internal-reflection"><span class="header-section-number">18.8.4</span> Example 4: Critical Angle and Total Internal Reflection</h3>
<p><strong>Question:</strong> The refractive index of a certain type of glass is 1.60. (a) Calculate the critical angle for this glass. (b) A ray of light inside this glass strikes the glass-air boundary at an angle of incidence of 45°. Will total internal reflection occur? Explain.</p>
<p><strong>Solution:</strong></p>
<p><strong>(a) Critical angle:</strong> <span class="math display">\[\sin c = \frac{1}{n} = \frac{1}{1.60} = 0.625\]</span> <span class="math display">\[c = \sin^{-1}(0.625) = \boxed{38.7^\circ}\]</span></p>
<p><strong>(b) Will TIR occur?</strong> - Angle of incidence <span class="math inline">\(i = 45^\circ\)</span></p>
<ul>
<li><p>Critical angle <span class="math inline">\(c = 38.7^\circ\)</span></p></li>
<li><p>Since <span class="math inline">\(i &gt; c\)</span> (<span class="math inline">\(45^\circ &gt; 38.7^\circ\)</span>) and light is travelling from denser (glass) to less dense (air) medium:</p></li>
<li><p><strong>Yes, total internal reflection will occur.</strong></p></li>
</ul>
<hr>
</section>
<section id="example-5-apparent-depth-calculation" class="level3" data-number="18.8.5">
<h3 data-number="18.8.5" class="anchored" data-anchor-id="example-5-apparent-depth-calculation"><span class="header-section-number">18.8.5</span> Example 5: Apparent Depth Calculation</h3>
<p><strong>Question:</strong> A fish is actually 1.2 m below the surface of a pond. The refractive index of water is 1.33. Calculate the apparent depth of the fish as seen by an observer directly above.</p>
<p><strong>Solution:</strong></p>
<p><strong>Step 1:</strong> Use the apparent depth formula: <span class="math display">\[n = \frac{\text{real depth}}{\text{apparent depth}}\]</span></p>
<p><strong>Step 2:</strong> Rearrange for apparent depth: <span class="math display">\[\text{apparent depth} = \frac{\text{real depth}}{n} = \frac{1.2}{1.33} = \boxed{0.90 \text{ m}}\]</span></p>
<p><strong>Interpretation:</strong> The fish appears to be only 0.90 m deep, not 1.2 m, due to refraction at the water-air boundary.</p>
<hr>
</section>
</section>
<section id="practice-questions" class="level2" data-number="18.9">
<h2 data-number="18.9" class="anchored" data-anchor-id="practice-questions"><span class="header-section-number">18.9</span> Practice Questions</h2>
<section id="core-level" class="level3" data-number="18.9.1">
<h3 data-number="18.9.1" class="anchored" data-anchor-id="core-level"><span class="header-section-number">18.9.1</span> Core Level</h3>
<ol type="1">
<li>Define the terms:</li>
</ol>
<ul>
<li><ol type="a">
<li>angle of incidence</li>
</ol></li>
<li><ol start="2" type="a">
<li>angle of reflection</li>
</ol></li>
<li><ol start="3" type="a">
<li>normal</li>
</ol></li>
</ul>
<ol start="2" type="1">
<li><p>State the law of reflection.</p></li>
<li><p>List four characteristics of an image formed by a plane mirror.</p></li>
<li><p>A ray of light strikes a mirror at an angle of 25° to the normal. Calculate:</p></li>
</ol>
<ul>
<li><ol type="a">
<li>the angle of reflection</li>
</ol></li>
<li><ol start="2" type="a">
<li>the angle between the incident ray and the mirror surface</li>
</ol></li>
</ul>
<ol start="5" type="1">
<li><p>Define refraction.</p></li>
<li><p>Explain why a pencil appears bent when partially immersed in water.</p></li>
<li><p>A ray of light enters glass (<span class="math inline">\(n = 1.5\)</span>) from air at an angle of incidence of 30°. Calculate the angle of refraction.</p></li>
<li><p>Define the term critical angle.</p></li>
<li><p>State two conditions necessary for total internal reflection to occur.</p></li>
<li><p>Give one application of total internal reflection.</p></li>
</ol>
</section>
<section id="extended-level" class="level3" data-number="18.9.2">
<h3 data-number="18.9.2" class="anchored" data-anchor-id="extended-level"><span class="header-section-number">18.9.2</span> Extended Level</h3>
<ol start="11" type="1">
<li>A person 1.6 m tall stands 3.0 m in front of a vertical plane mirror.</li>
</ol>
<ul>
<li><ol type="a">
<li>How tall is the image?</li>
</ol></li>
<li><ol start="2" type="a">
<li>How far behind the mirror is the image?</li>
</ol></li>
<li><ol start="3" type="a">
<li>If the person walks towards the mirror at 0.5 m/s, at what speed does the image approach the person?</li>
</ol></li>
</ul>
<ol start="12" type="1">
<li>Light travels from air into a liquid. The angle of incidence is 45° and the angle of refraction is 30°.</li>
</ol>
<ul>
<li><ol type="a">
<li>Calculate the refractive index of the liquid.</li>
</ol></li>
<li><ol start="2" type="a">
<li>Calculate the speed of light in the liquid. (Take <span class="math inline">\(c = 3.0 \times 10^8\)</span> m/s)</li>
</ol></li>
</ul>
<ol start="13" type="1">
<li>The critical angle for a certain material is 35°.</li>
</ol>
<ul>
<li><ol type="a">
<li>Calculate the refractive index of the material.</li>
</ol></li>
<li><ol start="2" type="a">
<li>Will total internal reflection occur if light inside the material strikes the boundary with air at an angle of 40°? Explain.</li>
</ol></li>
</ul>
<ol start="14" type="1">
<li>A swimming pool is 2.0 m deep. The refractive index of water is 1.33.</li>
</ol>
<ul>
<li><ol type="a">
<li>Calculate the apparent depth of the pool as seen from directly above.</li>
</ol></li>
<li><ol start="2" type="a">
<li>Explain why a swimmer at the bottom of the pool appears closer to the surface than they actually are.</li>
</ol></li>
</ul>
<ol start="15" type="1">
<li><p>Describe how optical fibres transmit light over long distances. Include reference to total internal reflection in your answer.</p></li>
<li><p>A ray of light passes through a rectangular glass block.</p></li>
</ol>
<ul>
<li><ol type="a">
<li>Sketch a ray diagram showing the path of the ray through the block.</li>
</ol></li>
<li><ol start="2" type="a">
<li>Explain why the emergent ray is parallel to the incident ray but laterally displaced.</li>
</ol></li>
</ul>
<hr>
</section>
</section>
<section id="laboratory-investigation" class="level2" data-number="18.10">
<h2 data-number="18.10" class="anchored" data-anchor-id="laboratory-investigation"><span class="header-section-number">18.10</span> Laboratory Investigation</h2>
<section id="experiment-15.1-investigating-refraction-using-a-rectangular-glass-block" class="level3" data-number="18.10.1">
<h3 data-number="18.10.1" class="anchored" data-anchor-id="experiment-15.1-investigating-refraction-using-a-rectangular-glass-block"><span class="header-section-number">18.10.1</span> Experiment 15.1: Investigating Refraction Using a Rectangular Glass Block</h3>
<p><strong>Objective:</strong> To verify Snell’s Law and determine the refractive index of glass by measuring angles of incidence and refraction.</p>
<p><strong>Apparatus:</strong> - Rectangular glass block</p>
<ul>
<li><p>Ray box with single slit</p></li>
<li><p>White paper</p></li>
<li><p>Protractor</p></li>
<li><p>Ruler</p></li>
<li><p>Pencil</p></li>
<li><p>Optical pins (optional alternative method)</p></li>
</ul>
<p><strong>Variables:</strong> - <strong>Independent:</strong> Angle of incidence (<span class="math inline">\(i\)</span>)</p>
<ul>
<li><p><strong>Dependent:</strong> Angle of refraction (<span class="math inline">\(r\)</span>)</p></li>
<li><p><strong>Controlled:</strong> Same glass block, same wavelength of light, same experimental setup</p></li>
</ul>
<p><strong>Procedure:</strong> 1. Place the glass block on a sheet of white paper and trace its outline.</p>
<ol start="2" type="1">
<li><p>Remove the block and draw a normal line at the centre of one of the longer faces.</p></li>
<li><p>Draw an incident ray at an angle of incidence <span class="math inline">\(i = 30^\circ\)</span> to the normal.</p></li>
<li><p>Replace the glass block exactly on its outline.</p></li>
<li><p>Direct a narrow ray of light from the ray box along the incident ray line.</p></li>
<li><p>Mark the point where the ray emerges from the opposite face of the block.</p></li>
<li><p>Remove the block and draw the refracted ray inside the block and the emergent ray.</p></li>
<li><p>Measure the angle of refraction <span class="math inline">\(r\)</span> inside the block.</p></li>
<li><p>Repeat steps 3–8 for angles of incidence: 40°, 50°, 60°, 70°.</p></li>
<li><p>Record results in a table and calculate <span class="math inline">\(\sin i\)</span>, <span class="math inline">\(\sin r\)</span>, and <span class="math inline">\(\frac{\sin i}{\sin r}\)</span> for each trial.</p></li>
</ol>
<p><strong>Data Table:</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 9%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 38%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Trial</th>
<th style="text-align: left;"><span class="math inline">\(i\)</span> (°)</th>
<th style="text-align: left;"><span class="math inline">\(r\)</span> (°)</th>
<th style="text-align: left;"><span class="math inline">\(\sin i\)</span></th>
<th style="text-align: left;"><span class="math inline">\(\sin r\)</span></th>
<th style="text-align: left;"><span class="math inline">\(n = \frac{\sin i}{\sin r}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">30</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;">40</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;">50</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">4</td>
<td style="text-align: left;">60</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">5</td>
<td style="text-align: left;">70</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
</tbody>
</table>
<p><strong>Analysis:</strong> 1. Calculate the average value of <span class="math inline">\(n\)</span> from your results.</p>
<ol start="2" type="1">
<li><p>Plot a graph of <span class="math inline">\(\sin i\)</span> (y-axis) against <span class="math inline">\(\sin r\)</span> (x-axis).</p></li>
<li><p>Determine the gradient of the best-fit line; this should equal the refractive index <span class="math inline">\(n\)</span>.</p></li>
<li><p>Compare your experimental <span class="math inline">\(n\)</span> with the accepted value for glass (~1.50).</p></li>
</ol>
<p><strong>Precautions:</strong> - ✓ Ensure the glass block is placed exactly on its outline for each trial</p>
<ul>
<li><p>✓ Use a narrow, well-defined ray for accurate angle measurement</p></li>
<li><p>✓ Measure angles from the normal, not from the surface</p></li>
<li><p>✓ Avoid parallax error when reading the protractor</p></li>
</ul>
<p><strong>Expected Results:</strong> - The graph of <span class="math inline">\(\sin i\)</span> against <span class="math inline">\(\sin r\)</span> should be a straight line through the origin</p>
<ul>
<li><p>The gradient should be approximately 1.50 for typical glass</p></li>
<li><p>The emergent ray should be parallel to the incident ray but laterally displaced</p></li>
</ul>
<p><strong>Conclusion Template:</strong> “The experiment verified Snell’s Law: the ratio <span class="math inline">\(\frac{\sin i}{\sin r}\)</span> was approximately constant, giving a refractive index of ______ for the glass block. This value is [close to/different from] the accepted value of 1.50, which may be due to [measurement uncertainties/variations in glass composition/etc.].”</p>
<p><strong>Extension (Supplement):</strong> - Repeat the experiment with a semicircular glass block to study the critical angle</p>
<ul>
<li><p>Investigate refraction for light travelling from glass to air to observe total internal reflection</p></li>
<li><p>Compare refractive indices of different transparent materials (e.g., acrylic, water)</p></li>
</ul>
<hr>
</section>
</section>
<section id="exam-style-questions" class="level2" data-number="18.11">
<h2 data-number="18.11" class="anchored" data-anchor-id="exam-style-questions"><span class="header-section-number">18.11</span> Exam-Style Questions</h2>
<section id="paper-1-style-multiple-choice" class="level3" data-number="18.11.1">
<h3 data-number="18.11.1" class="anchored" data-anchor-id="paper-1-style-multiple-choice"><span class="header-section-number">18.11.1</span> Paper 1 Style (Multiple Choice)</h3>
<ol type="1">
<li>Which statement correctly describes the law of reflection?</li>
</ol>
<p>A. The angle of incidence equals the angle between the incident ray and the mirror</p>
<p>B. The angle of incidence equals the angle of reflection, both measured from the normal</p>
<p>C. The incident ray and reflected ray are always perpendicular</p>
<p>D. The normal bisects the angle between the incident and reflected rays</p>
<ol start="2" type="1">
<li>An object is placed 40 cm in front of a plane mirror. How far is the image from the object?</li>
</ol>
<p>A. 20 cm</p>
<p>B. 40 cm</p>
<p>C. 80 cm</p>
<p>D. 160 cm</p>
<ol start="3" type="1">
<li>Light travels from air into glass. Which statement is correct?</li>
</ol>
<p>A. The light speeds up and bends away from the normal</p>
<p>B. The light speeds up and bends towards the normal</p>
<p>C. The light slows down and bends away from the normal</p>
<p>D. The light slows down and bends towards the normal</p>
<ol start="4" type="1">
<li>The refractive index of a material is 2.0. What is the critical angle for light travelling from this material to air?</li>
</ol>
<p>A. 25°</p>
<p>B. 30°</p>
<p>C. 45°</p>
<p>D. 60°</p>
<ol start="5" type="1">
<li>Which application uses total internal reflection?</li>
</ol>
<p>A. Plane mirror</p>
<p>B. Magnifying glass</p>
<p>C. Optical fibre</p>
<p>D. Pinhole camera</p>
</section>
<section id="paper-3-style-structured" class="level3" data-number="18.11.2">
<h3 data-number="18.11.2" class="anchored" data-anchor-id="paper-3-style-structured"><span class="header-section-number">18.11.2</span> Paper 3 Style (Structured)</h3>
<ol start="6" type="1">
<li><ol type="a">
<li>State the law of reflection. [1]</li>
</ol></li>
</ol>
<ol start="2" type="a">
<li><p>A ray of light strikes a plane mirror at an angle of 50° to the mirror surface.</p></li>
<li><p>Calculate the angle of incidence. [1]</p></li>
</ol>
<ol start="2" type="i">
<li><p>Calculate the angle of reflection. [1]</p></li>
<li><p>Sketch a labelled ray diagram to show the incident ray, reflected ray, normal, and both angles. [3]</p></li>
<li><p>List three characteristics of the image formed by a plane mirror. [3]</p></li>
</ol>
<ol start="7" type="1">
<li><ol type="a">
<li>Define refraction. [1]</li>
</ol></li>
</ol>
<ol start="2" type="a">
<li><p>Light travels from air into water (<span class="math inline">\(n = 1.33\)</span>) at an angle of incidence of 40°.</p></li>
<li><p>Calculate the angle of refraction. [3]</p></li>
</ol>
<ol start="2" type="i">
<li><p>Explain why the light ray bends towards the normal. [2]</p></li>
<li><p>A coin is placed at the bottom of a container filled with water. Explain why the coin appears to be at a shallower depth than it actually is. [2]</p></li>
</ol>
<ol start="8" type="1">
<li>(Extended) (a) Define the term critical angle. [1]</li>
</ol>
<ol start="2" type="a">
<li><p>The refractive index of diamond is 2.42.</p></li>
<li><p>Calculate the critical angle for diamond. [2]</p></li>
</ol>
<ol start="2" type="i">
<li><p>Explain why diamonds sparkle brilliantly. [2]</p></li>
<li><p>Describe how optical fibres use total internal reflection to transmit data. Include a labelled diagram in your answer. [4]</p></li>
</ol>
<ol start="9" type="1">
<li>(Extended) A student investigates refraction using a rectangular glass block.</li>
</ol>
<ol type="a">
<li><p>Describe the procedure the student should follow to measure the angle of refraction for a given angle of incidence. [4]</p></li>
<li><p>The student obtains the following</p></li>
</ol>
<table class="caption-top table">
<thead>
<tr class="header">
<th><span class="math inline">\(i\)</span> (°)</th>
<th>20</th>
<th>30</th>
<th>40</th>
<th>50</th>
<th>60</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(r\)</span> (°)</td>
<td>13</td>
<td>19</td>
<td>25</td>
<td>30</td>
<td>35</td>
</tr>
</tbody>
</table>
<ol type="i">
<li><p>Complete the table by calculating <span class="math inline">\(\sin i\)</span> and <span class="math inline">\(\sin r\)</span> for each pair of angles. [2]</p></li>
<li><p>Plot a graph of <span class="math inline">\(\sin i\)</span> (y-axis) against <span class="math inline">\(\sin r\)</span> (x-axis). [3]</p></li>
<li><p>Use your graph to determine the refractive index of the glass. [2]</p></li>
</ol>
<hr>
</section>
</section>
<section id="chapter-summary" class="level2" data-number="18.12">
<h2 data-number="18.12" class="anchored" data-anchor-id="chapter-summary"><span class="header-section-number">18.12</span> Chapter Summary</h2>
<section id="key-points-to-remember" class="level3" data-number="18.12.1">
<h3 data-number="18.12.1" class="anchored" data-anchor-id="key-points-to-remember"><span class="header-section-number">18.12.1</span> Key Points to Remember</h3>
<p>✓ <strong>Reflection</strong>: <span class="math inline">\(i = r\)</span>; incident ray, reflected ray, normal in same plane</p>
<p>✓ <strong>Plane mirror image</strong>: Same size, same distance behind mirror, virtual, upright, laterally inverted</p>
<p>✓ <strong>Refraction</strong>: Light bends due to change in speed when passing between media</p>
<p>✓ <strong>Snell’s Law</strong>: <span class="math inline">\(n = \frac{\sin i}{\sin r}\)</span> for air/vacuum → medium</p>
<p>✓ <strong>Refractive index</strong>: <span class="math inline">\(n = \frac{c}{v}\)</span>; higher <span class="math inline">\(n\)</span> = slower light = greater bending</p>
<p>✓ <strong>Critical angle</strong>: <span class="math inline">\(\sin c = \frac{1}{n}\)</span>; angle for which refraction angle = 90°</p>
<p>✓ <strong>Total internal reflection</strong>: Occurs when <span class="math inline">\(i &gt; c\)</span> and light travels denser → less dense</p>
<p>✓ <strong>Applications</strong>: Optical fibres, prisms, endoscopes, reflectors</p>
</section>
<section id="formulae-sheet" class="level3" data-number="18.12.2">
<h3 data-number="18.12.2" class="anchored" data-anchor-id="formulae-sheet"><span class="header-section-number">18.12.2</span> Formulae Sheet</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 30%">
<col style="width: 36%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Quantity</th>
<th style="text-align: left;">Formula</th>
<th style="text-align: left;">Variables</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Law of reflection</td>
<td style="text-align: left;"><span class="math inline">\(i = r\)</span></td>
<td style="text-align: left;"><span class="math inline">\(i\)</span>=angle of incidence, <span class="math inline">\(r\)</span>=angle of reflection</td>
</tr>
<tr class="even">
<td style="text-align: left;">Snell’s Law</td>
<td style="text-align: left;"><span class="math inline">\(n = \frac{\sin i}{\sin r}\)</span></td>
<td style="text-align: left;"><span class="math inline">\(n\)</span>=refractive index, <span class="math inline">\(i\)</span>=incidence angle (in air), <span class="math inline">\(r\)</span>=refraction angle</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Refractive index (speed)</td>
<td style="text-align: left;"><span class="math inline">\(n = \frac{c}{v}\)</span></td>
<td style="text-align: left;"><span class="math inline">\(c\)</span>=speed in vacuum (<span class="math inline">\(3.0 \times 10^8\)</span> m/s), <span class="math inline">\(v\)</span>=speed in medium</td>
</tr>
<tr class="even">
<td style="text-align: left;">Critical angle</td>
<td style="text-align: left;"><span class="math inline">\(\sin c = \frac{1}{n}\)</span></td>
<td style="text-align: left;"><span class="math inline">\(c\)</span>=critical angle, <span class="math inline">\(n\)</span>=refractive index of denser medium</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Apparent depth</td>
<td style="text-align: left;"><span class="math inline">\(n = \frac{\text{real depth}}{\text{apparent depth}}\)</span></td>
<td style="text-align: left;">For viewing objects through a plane boundary</td>
</tr>
</tbody>
</table>
<hr>
</section>
</section>
<section id="further-resources" class="level2" data-number="18.13">
<h2 data-number="18.13" class="anchored" data-anchor-id="further-resources"><span class="header-section-number">18.13</span> Further Resources</h2>
<section id="recommended-reading" class="level3" data-number="18.13.1">
<h3 data-number="18.13.1" class="anchored" data-anchor-id="recommended-reading"><span class="header-section-number">18.13.1</span> Recommended Reading</h3>
<ul>
<li><p>Cambridge IGCSE Physics Coursebook, Chapter 12 (Light: Reflection and Refraction)</p></li>
<li><p>Practical Work in Physics: Ray Optics Experiments</p></li>
</ul>
</section>
<section id="online-resources" class="level3" data-number="18.13.2">
<h3 data-number="18.13.2" class="anchored" data-anchor-id="online-resources"><span class="header-section-number">18.13.2</span> Online Resources</h3>
<ul>
<li><p>PhET Interactive Simulations: Bending Light, Geometric Optics</p></li>
<li><p>BBC Bitesize: Reflection, Refraction, Total Internal Reflection</p></li>
<li><p>University of Colorado: Ray Optics simulations</p></li>
</ul>
</section>
<section id="video-resources" class="level3" data-number="18.13.3">
<h3 data-number="18.13.3" class="anchored" data-anchor-id="video-resources"><span class="header-section-number">18.13.3</span> Video Resources</h3>
<ul>
<li><p>Demonstration: Ray tracing with plane mirrors and glass blocks</p></li>
<li><p>Animation: How optical fibres use total internal reflection</p></li>
<li><p>Real-world application: Telecommunications and endoscopy using optical fibres</p></li>
</ul>
<hr>
</section>
</section>
<section id="glossary" class="level2" data-number="18.14">
<h2 data-number="18.14" class="anchored" data-anchor-id="glossary"><span class="header-section-number">18.14</span> Glossary</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 66%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Term</th>
<th style="text-align: left;">Definition</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Angle of incidence (<span class="math inline">\(i\)</span>)</strong></td>
<td style="text-align: left;">Angle between the incident ray and the normal at the point of incidence</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Angle of reflection (<span class="math inline">\(r\)</span>)</strong></td>
<td style="text-align: left;">Angle between the reflected ray and the normal at the point of incidence</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Angle of refraction (<span class="math inline">\(r\)</span>)</strong></td>
<td style="text-align: left;">Angle between the refracted ray and the normal at the point of incidence</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Apparent depth</strong></td>
<td style="text-align: left;">The depth at which an object appears to be when viewed through a refracting medium</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Critical angle (<span class="math inline">\(c\)</span>)</strong></td>
<td style="text-align: left;">The angle of incidence in the denser medium for which the angle of refraction in the less dense medium is 90°</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Incident ray</strong></td>
<td style="text-align: left;">The ray of light approaching a boundary or reflecting surface</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Lateral inversion</strong></td>
<td style="text-align: left;">The swapping of left and right in an image formed by a plane mirror</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Normal</strong></td>
<td style="text-align: left;">An imaginary line perpendicular to a surface or boundary at the point of incidence</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Refracted ray</strong></td>
<td style="text-align: left;">The ray of light that has passed into a second medium and changed direction</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Refractive index (<span class="math inline">\(n\)</span>)</strong></td>
<td style="text-align: left;">Ratio of speed of light in vacuum to speed in medium; or <span class="math inline">\(\frac{\sin i}{\sin r}\)</span> for air → medium</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Reflection</strong></td>
<td style="text-align: left;">The rebounding of light at a surface; governed by <span class="math inline">\(i = r\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Refraction</strong></td>
<td style="text-align: left;">The bending of light as it passes from one medium to another due to a change in speed</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Total internal reflection</strong></td>
<td style="text-align: left;">Complete reflection of light within a denser medium when <span class="math inline">\(i &gt; c\)</span> at a boundary with a less dense medium</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Virtual image</strong></td>
<td style="text-align: left;">An image formed where light rays appear to come from but do not actually meet; cannot be captured on a screen</td>
</tr>
</tbody>
</table>
<hr>
<p><em>End of Chapter 15</em></p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
            // default icon
            link.classList.add("external");
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../chapters/14-wave-properties.html" class="pagination-link" aria-label="General Properties of Waves">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">General Properties of Waves</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../chapters/16-em-spectrum.html" class="pagination-link" aria-label="Electromagnetic Spectrum">
        <span class="nav-page-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Electromagnetic Spectrum</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>