<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Sugeng Riyanto, M.Sc.">
<meta name="dcterms.date" content="2026-01-01">

<title>20&nbsp; Sound – Cambridge IGCSE Physics 0625: Last-Minute Revision Guide</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapters/18-magnetism.html" rel="next">
<link href="../chapters/16-em-spectrum.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-845c23b38eaddc0f92fda52bfe77a8c8.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-932514a4c912dae26ceaa3c5ace84409.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/01-measurement.html">Core Content</a></li><li class="breadcrumb-item"><a href="../chapters/17-sound.html"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Sound</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Cambridge IGCSE Physics 0625: Last-Minute Revision Guide</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Cambridge IGCSE Physics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../syllabus-map.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Syllabus Mapping</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Preface</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Core Content</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/01-measurement.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Measurement of Physical Quantities</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/02-motion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Motion</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/03-mass-weight-density.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Mass, Weight and Density</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/04-forces.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Forces</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/05-moments-equilibrium.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Moments and Equilibrium</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/06-momentum.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Momentum</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/07-energy-stores.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Energy Stores</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/08-work-power.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Work and Power</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/09-pressure.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Pressure</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/10-kinetic-particle-model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Kinetic Particle Model of Matter</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/11-thermal-properties.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Thermal Properties</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/12-phase-changes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Phase Changes</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/13-thermal-transfer.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Thermal Transfer</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/14-wave-properties.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">General Properties of Waves</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/15-light-reflection-refraction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Light: Reflection and Refraction</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/16-em-spectrum.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Electromagnetic Spectrum</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/17-sound.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Sound</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/18-magnetism.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Simple Phenomena of Magnetism</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/19-electric-charge-circuits.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Electric Charge and Circuits</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/20-electrical-quantities.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Electrical Quantities</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/21-electromagnetic-effects.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Electromagnetic Effects</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/22-nuclear-physics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Nuclear Physics</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/23-space-physics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Space Physics</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Supporting Materials</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../back-matter/practical-skills.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Practical Skills</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../back-matter/maths-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Mathematical Data and Constants</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../back-matter/exam-technique.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Common Question Types</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../back-matter/formula-sheet.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Formula Sheet</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../back-matter/bibliography.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Bibliography and References</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../back-matter/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Cambridge IGCSE Physics Reference Guide</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul class="collapse">
  <li><a href="#learning-objectives" id="toc-learning-objectives" class="nav-link active" data-scroll-target="#learning-objectives"><span class="header-section-number">20.1</span> Learning Objectives</a></li>
  <li><a href="#production-and-nature-of-sound-waves" id="toc-production-and-nature-of-sound-waves" class="nav-link" data-scroll-target="#production-and-nature-of-sound-waves"><span class="header-section-number">20.2</span> 17.1 Production and Nature of Sound Waves</a></li>
  <li><a href="#transmission-of-sound" id="toc-transmission-of-sound" class="nav-link" data-scroll-target="#transmission-of-sound"><span class="header-section-number">20.3</span> 17.2 Transmission of Sound</a></li>
  <li><a href="#loudness-and-pitch" id="toc-loudness-and-pitch" class="nav-link" data-scroll-target="#loudness-and-pitch"><span class="header-section-number">20.4</span> 17.3 Loudness and Pitch</a></li>
  <li><a href="#echoes-and-ultrasound" id="toc-echoes-and-ultrasound" class="nav-link" data-scroll-target="#echoes-and-ultrasound"><span class="header-section-number">20.5</span> 17.4 Echoes and Ultrasound</a></li>
  <li><a href="#key-concepts-summary" id="toc-key-concepts-summary" class="nav-link" data-scroll-target="#key-concepts-summary"><span class="header-section-number">20.6</span> Key Concepts Summary</a></li>
  <li><a href="#common-misconceptions" id="toc-common-misconceptions" class="nav-link" data-scroll-target="#common-misconceptions"><span class="header-section-number">20.7</span> Common Misconceptions</a></li>
  <li><a href="#worked-examples" id="toc-worked-examples" class="nav-link" data-scroll-target="#worked-examples"><span class="header-section-number">20.8</span> Worked Examples</a></li>
  <li><a href="#practice-questions" id="toc-practice-questions" class="nav-link" data-scroll-target="#practice-questions"><span class="header-section-number">20.9</span> Practice Questions</a></li>
  <li><a href="#laboratory-investigation" id="toc-laboratory-investigation" class="nav-link" data-scroll-target="#laboratory-investigation"><span class="header-section-number">20.10</span> Laboratory Investigation</a></li>
  <li><a href="#exam-style-questions" id="toc-exam-style-questions" class="nav-link" data-scroll-target="#exam-style-questions"><span class="header-section-number">20.11</span> Exam-Style Questions</a></li>
  <li><a href="#chapter-summary" id="toc-chapter-summary" class="nav-link" data-scroll-target="#chapter-summary"><span class="header-section-number">20.12</span> Chapter Summary</a></li>
  <li><a href="#further-resources" id="toc-further-resources" class="nav-link" data-scroll-target="#further-resources"><span class="header-section-number">20.13</span> Further Resources</a></li>
  <li><a href="#glossary" id="toc-glossary" class="nav-link" data-scroll-target="#glossary"><span class="header-section-number">20.14</span> Glossary</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/01-measurement.html">Core Content</a></li><li class="breadcrumb-item"><a href="../chapters/17-sound.html"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Sound</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Sound</span></h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Sugeng Riyanto, M.Sc. </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">January 1, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="learning-objectives" class="level2" data-number="20.1">
<h2 data-number="20.1" class="anchored" data-anchor-id="learning-objectives"><span class="header-section-number">20.1</span> Learning Objectives</h2>
<p>By the end of this chapter, you will be able to:</p>
<p><strong>Core Content:</strong></p>
<ul>
<li><p>Describe the production of sound by vibrating sources</p></li>
<li><p>Describe the longitudinal nature of sound waves</p></li>
<li><p>State the approximate range of frequencies audible to humans as 20 Hz to 20 000 Hz</p></li>
<li><p>Know that a medium is needed to transmit sound waves</p></li>
<li><p>Know that the speed of sound in air is approximately 330–350 m/s</p></li>
<li><p>Describe a method involving a measurement of distance and time for determining the speed of sound in air</p></li>
<li><p>Describe how changes in amplitude and frequency affect the loudness and pitch of sound waves</p></li>
<li><p>Describe an echo as the reflection of sound waves</p></li>
<li><p>Define ultrasound as sound with a frequency higher than 20 kHz</p></li>
</ul>
<p><strong>Supplement (Extended):</strong></p>
<ul>
<li><p>Describe compression and rarefaction</p></li>
<li><p>Know that, in general, sound travels faster in solids than in liquids and faster in liquids than in gases</p></li>
<li><p>Describe the uses of ultrasound in non-destructive testing of materials, medical scanning of soft tissue and sonar including calculation of depth or distance from time and wave speed</p></li>
</ul>
<hr>
</section>
<section id="production-and-nature-of-sound-waves" class="level2" data-number="20.2">
<h2 data-number="20.2" class="anchored" data-anchor-id="production-and-nature-of-sound-waves"><span class="header-section-number">20.2</span> 17.1 Production and Nature of Sound Waves</h2>
<section id="how-is-sound-produced" class="level3" data-number="20.2.1">
<h3 data-number="20.2.1" class="anchored" data-anchor-id="how-is-sound-produced"><span class="header-section-number">20.2.1</span> How Is Sound Produced?</h3>
<p>Sound is produced by <strong>vibrating sources</strong> placed in a medium.</p>
<ul>
<li><p>When a guitar string vibrates, it pushes and pulls on the surrounding air particles</p></li>
<li><p>When vocal cords vibrate, they create pressure variations in the air</p></li>
<li><p>When a drum skin is struck, it vibrates and transfers energy to the air</p></li>
</ul>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Key Concept:</strong> Without vibration, there is no sound. If you stop a vibrating object (e.g., by placing your hand on a ringing bell), the sound stops because the vibration stops.</p>
</div>
</div>
</section>
<section id="the-longitudinal-nature-of-sound-waves" class="level3" data-number="20.2.2">
<h3 data-number="20.2.2" class="anchored" data-anchor-id="the-longitudinal-nature-of-sound-waves"><span class="header-section-number">20.2.2</span> The Longitudinal Nature of Sound Waves</h3>
<p>Sound waves are <strong>longitudinal waves</strong>. This means:</p>
<ul>
<li><p>The direction of vibration of particles is <strong>parallel</strong> to the direction of wave propagation</p></li>
<li><p>Sound waves propagate as a series of <strong>compressions</strong> and <strong>rarefactions</strong></p></li>
</ul>
<table class="caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 31%">
<col style="width: 53%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Term</th>
<th style="text-align: left;">Description</th>
<th style="text-align: left;">Particle Arrangement</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Compression</strong></td>
<td style="text-align: left;">Region where air pressure is higher than surrounding pressure</td>
<td style="text-align: left;">Particles are close together</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Rarefaction</strong></td>
<td style="text-align: left;">Region where air pressure is lower than surrounding pressure</td>
<td style="text-align: left;">Particles are spread apart</td>
</tr>
</tbody>
</table>
<p><strong>Visual representation of a sound wave:</strong></p>
<pre><code>Direction of wave propagation →

Compression    Rarefaction    Compression    Rarefaction
[|||||]        [   ]          [|||||]        [   ]
particles      particles      particles      particles
close          spread         close          spread
together       apart          together       apart</code></pre>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Important:</strong> Do not confuse the motion of individual particles with the motion of the wave. Particles oscillate back and forth about fixed positions; they do not travel with the wave.</p>
</div>
</div>
</section>
<section id="the-audible-range-of-human-hearing" class="level3" data-number="20.2.3">
<h3 data-number="20.2.3" class="anchored" data-anchor-id="the-audible-range-of-human-hearing"><span class="header-section-number">20.2.3</span> The Audible Range of Human Hearing</h3>
<p>The human ear can detect sound waves within a specific range of frequencies:</p>
<ul>
<li><p><strong>Lower limit</strong>: approximately <strong>20 Hz</strong></p></li>
<li><p><strong>Upper limit</strong>: approximately <strong>20 000 Hz</strong> (or 20 kHz)</p></li>
</ul>
<p><strong>Terminology:</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Term</th>
<th style="text-align: left;">Frequency Range</th>
<th style="text-align: left;">Audible to Humans?</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Infrasound</strong></td>
<td style="text-align: left;">Below 20 Hz</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Audible sound</strong></td>
<td style="text-align: left;">20 Hz to 20 kHz</td>
<td style="text-align: left;">Yes</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Ultrasound</strong></td>
<td style="text-align: left;">Above 20 kHz</td>
<td style="text-align: left;">No</td>
</tr>
</tbody>
</table>
<p><strong>Note:</strong> The upper limit of hearing decreases with age. Many adults cannot hear sounds above 15–17 kHz.</p>
<hr>
</section>
</section>
<section id="transmission-of-sound" class="level2" data-number="20.3">
<h2 data-number="20.3" class="anchored" data-anchor-id="transmission-of-sound"><span class="header-section-number">20.3</span> 17.2 Transmission of Sound</h2>
<section id="why-is-a-medium-needed" class="level3" data-number="20.3.1">
<h3 data-number="20.3.1" class="anchored" data-anchor-id="why-is-a-medium-needed"><span class="header-section-number">20.3.1</span> Why Is a Medium Needed?</h3>
<p>Sound waves require a <strong>medium</strong> (solid, liquid, or gas) to travel because:</p>
<ul>
<li><p>Sound is produced by particle vibrations</p></li>
<li><p>These vibrations must be transferred from one particle to the next</p></li>
<li><p>In a vacuum, there are no particles to vibrate → sound cannot travel</p></li>
</ul>
<p><strong>Demonstration: The Bell Jar Experiment</strong></p>
<ol type="1">
<li><p>An electric bell is suspended inside a sealed bell jar</p></li>
<li><p>When the bell rings with air inside, the sound is clearly heard</p></li>
<li><p>As air is pumped out, the sound becomes fainter</p></li>
<li><p>When a near-vacuum is achieved, the sound cannot be heard (though the bell is still visibly vibrating)</p></li>
</ol>
<p><strong>Conclusion:</strong> Sound cannot travel through a vacuum.</p>
</section>
<section id="speed-of-sound-in-different-media" class="level3" data-number="20.3.2">
<h3 data-number="20.3.2" class="anchored" data-anchor-id="speed-of-sound-in-different-media"><span class="header-section-number">20.3.2</span> Speed of Sound in Different Media</h3>
<p>The speed of sound depends on the medium through which it travels:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Medium</th>
<th style="text-align: left;">Approximate Speed of Sound (m/s)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Air (at 20°C)</td>
<td style="text-align: left;">330–350</td>
</tr>
<tr class="even">
<td style="text-align: left;">Water</td>
<td style="text-align: left;">≈ 1500</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Steel</td>
<td style="text-align: left;">≈ 5000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Granite</td>
<td style="text-align: left;">≈ 5400</td>
</tr>
</tbody>
</table>
<p><strong>General rule:</strong> Sound travels fastest in solids, slower in liquids, and slowest in gases.</p>
<p><strong>Explanation using particle model:</strong></p>
<ul>
<li><p>In solids, particles are closely packed → vibrations transfer quickly between particles</p></li>
<li><p>In liquids, particles are slightly further apart → transfer is slower</p></li>
<li><p>In gases, particles are far apart → transfer is slowest</p></li>
</ul>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Key Insight:</strong> The speed of sound also depends on temperature. In air, sound travels faster at higher temperatures because particles have more kinetic energy and collide more frequently.</p>
</div>
</div>
</section>
<section id="measuring-the-speed-of-sound-in-air" class="level3" data-number="20.3.3">
<h3 data-number="20.3.3" class="anchored" data-anchor-id="measuring-the-speed-of-sound-in-air"><span class="header-section-number">20.3.3</span> Measuring the Speed of Sound in Air</h3>
<p><strong>Method: Distance–Time Measurement</strong></p>
<p><strong>Apparatus:</strong></p>
<ul>
<li><p>Two observers (A and B) positioned a known distance apart (e.g., 500 m)</p></li>
<li><p>Electronic starting pistol (produces flash and sound simultaneously)</p></li>
<li><p>Stopwatch</p></li>
<li><p>Measuring tape</p></li>
</ul>
<p><strong>Procedure:</strong></p>
<ol type="1">
<li><p>Observer A fires the electronic starting pistol</p></li>
<li><p>Observer B starts the stopwatch when seeing the flash (light travels almost instantaneously)</p></li>
<li><p>Observer B stops the stopwatch when hearing the sound</p></li>
<li><p>Record the time interval <span class="math inline">\(t\)</span></p></li>
<li><p>Calculate speed: <span class="math inline">\(v = \frac{d}{t}\)</span></p></li>
</ol>
<p><strong>Example calculation:</strong></p>
<ul>
<li><p>Distance <span class="math inline">\(d = 500 \text{ m}\)</span></p></li>
<li><p>Time <span class="math inline">\(t = 1.5 \text{ s}\)</span></p></li>
<li><p>Speed <span class="math inline">\(v = \frac{500}{1.5} = 333 \text{ m/s}\)</span></p></li>
</ul>
<p><strong>Precautions:</strong></p>
<ul>
<li><p>✓ Repeat the experiment and take an average to minimise random errors</p></li>
<li><p>✓ Interchange positions of observers to cancel wind effects</p></li>
<li><p>✓ Use a large distance to reduce timing error relative to total time</p></li>
</ul>
<hr>
</section>
</section>
<section id="loudness-and-pitch" class="level2" data-number="20.4">
<h2 data-number="20.4" class="anchored" data-anchor-id="loudness-and-pitch"><span class="header-section-number">20.4</span> 17.3 Loudness and Pitch</h2>
<section id="what-affects-loudness" class="level3" data-number="20.4.1">
<h3 data-number="20.4.1" class="anchored" data-anchor-id="what-affects-loudness"><span class="header-section-number">20.4.1</span> What Affects Loudness?</h3>
<p><strong>Loudness</strong> is related to the <strong>amplitude</strong> of a sound wave.</p>
<ul>
<li><p>Larger amplitude → louder sound</p></li>
<li><p>Smaller amplitude → softer sound</p></li>
</ul>
<p><strong>Particle explanation:</strong></p>
<ul>
<li><p>Larger amplitude means particles oscillate with greater displacement</p></li>
<li><p>This creates larger pressure variations (greater difference between compressions and rarefactions)</p></li>
<li><p>The ear detects these larger pressure variations as a louder sound</p></li>
</ul>
</section>
<section id="what-affects-pitch" class="level3" data-number="20.4.2">
<h3 data-number="20.4.2" class="anchored" data-anchor-id="what-affects-pitch"><span class="header-section-number">20.4.2</span> What Affects Pitch?</h3>
<p><strong>Pitch</strong> is related to the <strong>frequency</strong> of a sound wave.</p>
<ul>
<li><p>Higher frequency → higher pitch</p></li>
<li><p>Lower frequency → lower pitch</p></li>
</ul>
<p><strong>Particle explanation:</strong></p>
<ul>
<li><p>Higher frequency means particles oscillate more times per second</p></li>
<li><p>The ear interprets more frequent pressure variations as a higher-pitched sound</p></li>
</ul>
</section>
<section id="visualising-sound-waves-with-a-c.r.o." class="level3" data-number="20.4.3">
<h3 data-number="20.4.3" class="anchored" data-anchor-id="visualising-sound-waves-with-a-c.r.o."><span class="header-section-number">20.4.3</span> Visualising Sound Waves with a C.R.O.</h3>
<p>A cathode-ray oscilloscope (c.r.o.) connected to a microphone can display sound waveforms:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 47%">
<col style="width: 52%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Waveform Feature</th>
<th style="text-align: left;">What It Represents</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Height of wave (from rest position)</td>
<td style="text-align: left;">Amplitude → loudness</td>
</tr>
<tr class="even">
<td style="text-align: left;">Distance between successive peaks</td>
<td style="text-align: left;">Wavelength → related to frequency and pitch</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Number of waves per second on screen</td>
<td style="text-align: left;">Frequency → pitch</td>
</tr>
</tbody>
</table>
<p><strong>Example comparisons:</strong></p>
<ul>
<li><p>A loud, low-pitched sound: large amplitude, widely spaced peaks</p></li>
<li><p>A soft, high-pitched sound: small amplitude, closely spaced peaks</p></li>
</ul>
<hr>
</section>
</section>
<section id="echoes-and-ultrasound" class="level2" data-number="20.5">
<h2 data-number="20.5" class="anchored" data-anchor-id="echoes-and-ultrasound"><span class="header-section-number">20.5</span> 17.4 Echoes and Ultrasound</h2>
<section id="what-is-an-echo" class="level3" data-number="20.5.1">
<h3 data-number="20.5.1" class="anchored" data-anchor-id="what-is-an-echo"><span class="header-section-number">20.5.1</span> What Is an Echo?</h3>
<p>An <strong>echo</strong> is the <strong>reflection of sound waves</strong> from a hard, flat surface.</p>
<p><strong>How echoes form:</strong></p>
<ol type="1">
<li><p>Sound waves travel from a source towards a surface (e.g., a wall or cliff)</p></li>
<li><p>The waves strike the surface and are reflected back</p></li>
<li><p>The reflected waves reach the listener after a time delay</p></li>
</ol>
<p><strong>Law of reflection for sound:</strong></p>
<ul>
<li><p>Angle of incidence = Angle of reflection</p></li>
<li><p>Both angles measured from the normal to the reflecting surface</p></li>
</ul>
<p><strong>Calculating distance using echoes:</strong></p>
<p><span class="math display">\[d = \frac{v \times t}{2}\]</span></p>
<p>Where: - <span class="math inline">\(d\)</span> = distance to reflecting surface (m)</p>
<ul>
<li><p><span class="math inline">\(v\)</span> = speed of sound in the medium (m/s)</p></li>
<li><p><span class="math inline">\(t\)</span> = time for echo to return (s)</p></li>
<li><p>Divide by 2 because sound travels to the surface and back</p></li>
</ul>
<p><strong>Worked Example: Echo Calculation</strong></p>
<p><strong>Question:</strong> A ship sends a sound pulse downwards into the sea. An echo from the seabed is received 0.4 s later. If the speed of sound in seawater is 1500 m/s, calculate the depth of the sea.</p>
<p><strong>Solution:</strong></p>
<p><strong>Step 1:</strong> Identify values - <span class="math inline">\(v = 1500 \text{ m/s}\)</span></p>
<ul>
<li><span class="math inline">\(t = 0.4 \text{ s}\)</span></li>
</ul>
<p><strong>Step 2:</strong> Apply formula <span class="math display">\[d = \frac{v \times t}{2} = \frac{1500 \times 0.4}{2} = \boxed{300 \text{ m}}\]</span></p>
<hr>
</section>
<section id="what-is-ultrasound" class="level3" data-number="20.5.2">
<h3 data-number="20.5.2" class="anchored" data-anchor-id="what-is-ultrasound"><span class="header-section-number">20.5.2</span> What Is Ultrasound?</h3>
<p><strong>Ultrasound</strong> is sound with a frequency <strong>higher than 20 kHz</strong> (above the upper limit of human hearing).</p>
</section>
<section id="uses-of-ultrasound" class="level3" data-number="20.5.3">
<h3 data-number="20.5.3" class="anchored" data-anchor-id="uses-of-ultrasound"><span class="header-section-number">20.5.3</span> Uses of Ultrasound</h3>
<section id="non-destructive-testing-of-materials" class="level4" data-number="20.5.3.1">
<h4 data-number="20.5.3.1" class="anchored" data-anchor-id="non-destructive-testing-of-materials"><span class="header-section-number">20.5.3.1</span> 1. Non-Destructive Testing of Materials</h4>
<ul>
<li><p>Ultrasound is sent through materials such as metal pipes or concrete slabs</p></li>
<li><p>Defects (cracks, cavities) reflect or scatter the ultrasound</p></li>
<li><p>By analysing the reflected signals, engineers can locate and size defects without damaging the material</p></li>
</ul>
</section>
<section id="medical-scanning-of-soft-tissue" class="level4" data-number="20.5.3.2">
<h4 data-number="20.5.3.2" class="anchored" data-anchor-id="medical-scanning-of-soft-tissue"><span class="header-section-number">20.5.3.2</span> 2. Medical Scanning of Soft Tissue</h4>
<ul>
<li><p>Ultrasound pulses are sent into the body via a transducer</p></li>
<li><p>Different tissues reflect ultrasound to different degrees</p></li>
<li><p>The time taken for echoes to return is used to build up an image of internal structures</p></li>
<li><p><strong>Advantages over X-rays:</strong> Ultrasound is non-ionising and safer for scanning foetuses and soft tissues</p></li>
</ul>
</section>
<section id="sonar-sound-navigation-and-ranging" class="level4" data-number="20.5.3.3">
<h4 data-number="20.5.3.3" class="anchored" data-anchor-id="sonar-sound-navigation-and-ranging"><span class="header-section-number">20.5.3.3</span> 3. Sonar (Sound Navigation and Ranging)</h4>
<ul>
<li><p>Ships use sonar to detect the depth of the seabed or the position of objects underwater</p></li>
<li><p>A pulse of ultrasound is sent downwards; the time for the echo to return is measured</p></li>
<li><p>Depth is calculated using <span class="math inline">\(d = \frac{v \times t}{2}\)</span></p></li>
</ul>
<p><strong>Worked Example: Sonar Calculation</strong></p>
<p><strong>Question:</strong> A submarine uses sonar to detect a shoal of fish. The ultrasound pulse returns after 0.12 s. If the speed of sound in seawater is 1500 m/s, calculate the distance to the shoal.</p>
<p><strong>Solution:</strong></p>
<p><strong>Step 1:</strong> Identify values - <span class="math inline">\(v = 1500 \text{ m/s}\)</span></p>
<ul>
<li><span class="math inline">\(t = 0.12 \text{ s}\)</span></li>
</ul>
<p><strong>Step 2:</strong> Apply formula <span class="math display">\[d = \frac{v \times t}{2} = \frac{1500 \times 0.12}{2} = \boxed{90 \text{ m}}\]</span></p>
<hr>
</section>
</section>
</section>
<section id="key-concepts-summary" class="level2" data-number="20.6">
<h2 data-number="20.6" class="anchored" data-anchor-id="key-concepts-summary"><span class="header-section-number">20.6</span> Key Concepts Summary</h2>
<section id="core-concepts" class="level3" data-number="20.6.1">
<h3 data-number="20.6.1" class="anchored" data-anchor-id="core-concepts"><span class="header-section-number">20.6.1</span> Core Concepts</h3>
<ol type="1">
<li><p><strong>Sound production</strong>: Sound is produced by vibrating sources in a medium</p></li>
<li><p><strong>Longitudinal waves</strong>: Sound waves consist of compressions and rarefactions; particle vibration is parallel to wave propagation</p></li>
<li><p><strong>Audible range</strong>: Humans can hear frequencies from approximately 20 Hz to 20 kHz</p></li>
<li><p><strong>Medium required</strong>: Sound cannot travel through a vacuum; it requires a medium (solid, liquid, or gas)</p></li>
<li><p><strong>Speed of sound</strong>: Approximately 330–350 m/s in air; faster in liquids and solids</p></li>
<li><p><strong>Speed measurement</strong>: Use distance–time method with flash and sound from a starting pistol</p></li>
<li><p><strong>Loudness and pitch</strong>: Loudness depends on amplitude; pitch depends on frequency</p></li>
<li><p><strong>Echoes</strong>: Reflection of sound waves; used to calculate distances</p></li>
<li><p><strong>Ultrasound</strong>: Sound with frequency &gt; 20 kHz; used in testing, medical scanning, and sonar</p></li>
</ol>
</section>
<section id="extended-concepts" class="level3" data-number="20.6.2">
<h3 data-number="20.6.2" class="anchored" data-anchor-id="extended-concepts"><span class="header-section-number">20.6.2</span> Extended Concepts</h3>
<ol start="10" type="1">
<li><p><strong>Compression and rarefaction</strong>: Regions of high and low pressure in a longitudinal sound wave</p></li>
<li><p><strong>Speed comparison</strong>: Sound travels fastest in solids, slower in liquids, slowest in gases</p></li>
<li><p><strong>Ultrasound applications</strong>: Non-destructive testing, medical imaging, sonar depth/distance calculations</p></li>
</ol>
<hr>
</section>
</section>
<section id="common-misconceptions" class="level2" data-number="20.7">
<h2 data-number="20.7" class="anchored" data-anchor-id="common-misconceptions"><span class="header-section-number">20.7</span> Common Misconceptions</h2>
<section id="misconception-1-sound-can-travel-through-a-vacuum" class="level3" data-number="20.7.1">
<h3 data-number="20.7.1" class="anchored" data-anchor-id="misconception-1-sound-can-travel-through-a-vacuum"><span class="header-section-number">20.7.1</span> ⚠️ Misconception 1: “Sound can travel through a vacuum”</h3>
<p><strong>Incorrect</strong>: “Sound from explosions in space movies is realistic”</p>
<p><strong>Correct</strong>: - Sound requires a medium (particles) to transfer vibrations</p>
<ul>
<li><p>In a vacuum, there are no particles → sound cannot propagate</p></li>
<li><p>Space is a near-vacuum → no sound can travel through it</p></li>
</ul>
<hr>
</section>
<section id="misconception-2-particles-travel-with-the-sound-wave" class="level3" data-number="20.7.2">
<h3 data-number="20.7.2" class="anchored" data-anchor-id="misconception-2-particles-travel-with-the-sound-wave"><span class="header-section-number">20.7.2</span> ⚠️ Misconception 2: “Particles travel with the sound wave”</h3>
<p><strong>Incorrect</strong>: “Air molecules move from the speaker to your ear when you hear music”</p>
<p><strong>Correct</strong>: - Particles oscillate back and forth about fixed positions</p>
<ul>
<li><p>They transfer energy to neighbouring particles through collisions</p></li>
<li><p>Only the <strong>wave pattern and energy</strong> travel forward, not the particles themselves</p></li>
</ul>
<hr>
</section>
<section id="misconception-3-loudness-depends-on-frequency" class="level3" data-number="20.7.3">
<h3 data-number="20.7.3" class="anchored" data-anchor-id="misconception-3-loudness-depends-on-frequency"><span class="header-section-number">20.7.3</span> ⚠️ Misconception 3: “Loudness depends on frequency”</h3>
<p><strong>Incorrect</strong>: “High-pitched sounds are always louder than low-pitched sounds”</p>
<p><strong>Correct</strong>: - <strong>Loudness</strong> depends on <strong>amplitude</strong> (size of pressure variations)</p>
<ul>
<li><p><strong>Pitch</strong> depends on <strong>frequency</strong> (number of vibrations per second)</p></li>
<li><p>A low-pitched sound can be very loud if it has large amplitude</p></li>
</ul>
<hr>
</section>
<section id="misconception-4-ultrasound-is-harmful-because-it-is-ultra" class="level3" data-number="20.7.4">
<h3 data-number="20.7.4" class="anchored" data-anchor-id="misconception-4-ultrasound-is-harmful-because-it-is-ultra"><span class="header-section-number">20.7.4</span> ⚠️ Misconception 4: “Ultrasound is harmful because it is ‘ultra’”</h3>
<p><strong>Incorrect</strong>: “Ultrasound is dangerous because it is very high frequency”</p>
<p><strong>Correct</strong>: - Ultrasound is <strong>non-ionising</strong> radiation and is generally safe at diagnostic intensities</p>
<ul>
<li><p>It is preferred over X-rays for scanning foetuses because it does not damage cells</p></li>
<li><p>Harm depends on <strong>intensity and exposure time</strong>, not just frequency</p></li>
</ul>
<hr>
</section>
<section id="misconception-5-echoes-are-a-different-type-of-sound" class="level3" data-number="20.7.5">
<h3 data-number="20.7.5" class="anchored" data-anchor-id="misconception-5-echoes-are-a-different-type-of-sound"><span class="header-section-number">20.7.5</span> ⚠️ Misconception 5: “Echoes are a different type of sound”</h3>
<p><strong>Incorrect</strong>: “An echo is a special kind of sound wave”</p>
<p><strong>Correct</strong>: - An echo is simply a <strong>reflected sound wave</strong></p>
<ul>
<li><p>It has the same frequency, speed, and wavelength as the original sound</p></li>
<li><p>The only difference is the direction of propagation and the time delay</p></li>
</ul>
<hr>
</section>
<section id="misconception-6-sound-travels-at-the-same-speed-in-all-materials" class="level3" data-number="20.7.6">
<h3 data-number="20.7.6" class="anchored" data-anchor-id="misconception-6-sound-travels-at-the-same-speed-in-all-materials"><span class="header-section-number">20.7.6</span> ⚠️ Misconception 6: “Sound travels at the same speed in all materials”</h3>
<p><strong>Incorrect</strong>: “Sound travels at 340 m/s everywhere”</p>
<p><strong>Correct</strong>: - Speed of sound depends on the <strong>medium</strong> and its properties (density, elasticity, temperature)</p>
<ul>
<li><p>In air: ~330–350 m/s; in water: ~1500 m/s; in steel: ~5000 m/s</p></li>
<li><p>Temperature also affects speed: sound travels faster in warmer air</p></li>
</ul>
<hr>
</section>
<section id="misconception-7-ultrasound-cannot-be-used-for-distance-measurement" class="level3" data-number="20.7.7">
<h3 data-number="20.7.7" class="anchored" data-anchor-id="misconception-7-ultrasound-cannot-be-used-for-distance-measurement"><span class="header-section-number">20.7.7</span> ⚠️ Misconception 7: “Ultrasound cannot be used for distance measurement”</h3>
<p><strong>Incorrect</strong>: “Ultrasound is only for medical imaging”</p>
<p><strong>Correct</strong>: - Ultrasound is ideal for distance measurement because: - High frequency → short wavelength → precise measurements</p>
<ul>
<li><p>Can be directed in narrow beams</p></li>
<li><p>Reflects well from boundaries between different materials</p></li>
<li><p>Used in sonar, parking sensors, and industrial thickness gauging</p></li>
</ul>
<hr>
</section>
</section>
<section id="worked-examples" class="level2" data-number="20.8">
<h2 data-number="20.8" class="anchored" data-anchor-id="worked-examples"><span class="header-section-number">20.8</span> Worked Examples</h2>
<section id="example-1-frequency-and-period" class="level3" data-number="20.8.1">
<h3 data-number="20.8.1" class="anchored" data-anchor-id="example-1-frequency-and-period"><span class="header-section-number">20.8.1</span> Example 1: Frequency and Period</h3>
<p><strong>Question:</strong> A tuning fork vibrates at a frequency of 440 Hz. Calculate: (a) the period of one vibration (b) the number of complete vibrations in 2.5 seconds</p>
<p><strong>Solution:</strong></p>
<p><strong>(a) Period:</strong> <span class="math display">\[T = \frac{1}{f} = \frac{1}{440} = \boxed{0.00227 \text{ s} = 2.27 \text{ ms}}\]</span></p>
<p><strong>(b) Number of vibrations:</strong> <span class="math display">\[\text{Number} = f \times t = 440 \times 2.5 = \boxed{1100 \text{ vibrations}}\]</span></p>
<hr>
</section>
<section id="example-2-speed-of-sound-calculation" class="level3" data-number="20.8.2">
<h3 data-number="20.8.2" class="anchored" data-anchor-id="example-2-speed-of-sound-calculation"><span class="header-section-number">20.8.2</span> Example 2: Speed of Sound Calculation</h3>
<p><strong>Question:</strong> A student stands 170 m from a large wall and claps her hands. She hears the echo 1.0 s later. Calculate the speed of sound in air.</p>
<p><strong>Solution:</strong></p>
<p><strong>Step 1:</strong> Identify that sound travels to the wall and back <span class="math display">\[\text{Total distance} = 2 \times 170 = 340 \text{ m}\]</span></p>
<p><strong>Step 2:</strong> Apply speed formula <span class="math display">\[v = \frac{\text{distance}}{\text{time}} = \frac{340}{1.0} = \boxed{340 \text{ m/s}}\]</span></p>
<hr>
</section>
<section id="example-3-ultrasound-in-medical-scanning" class="level3" data-number="20.8.3">
<h3 data-number="20.8.3" class="anchored" data-anchor-id="example-3-ultrasound-in-medical-scanning"><span class="header-section-number">20.8.3</span> Example 3: Ultrasound in Medical Scanning</h3>
<p><strong>Question:</strong> An ultrasound scanner sends a pulse into a patient’s abdomen. The pulse reflects off the foetus and returns to the scanner after 0.00012 s. If the speed of ultrasound in soft tissue is 1540 m/s, calculate the depth of the foetus below the scanner.</p>
<p><strong>Solution:</strong></p>
<p><strong>Step 1:</strong> Identify values - <span class="math inline">\(v = 1540 \text{ m/s}\)</span></p>
<ul>
<li><span class="math inline">\(t = 0.00012 \text{ s}\)</span></li>
</ul>
<p><strong>Step 2:</strong> Apply echo formula <span class="math display">\[d = \frac{v \times t}{2} = \frac{1540 \times 0.00012}{2} = \boxed{0.0924 \text{ m} = 9.24 \text{ cm}}\]</span></p>
<hr>
</section>
<section id="example-4-comparing-loudness-and-pitch" class="level3" data-number="20.8.4">
<h3 data-number="20.8.4" class="anchored" data-anchor-id="example-4-comparing-loudness-and-pitch"><span class="header-section-number">20.8.4</span> Example 4: Comparing Loudness and Pitch</h3>
<p><strong>Question:</strong> Two sound waves are displayed on a c.r.o. Wave A has an amplitude of 2.0 cm and a wavelength of 4.0 cm. Wave B has an amplitude of 1.0 cm and a wavelength of 2.0 cm. The time base is the same for both. Compare the loudness and pitch of the two sounds.</p>
<p><strong>Solution:</strong></p>
<p><strong>Loudness comparison:</strong> - Amplitude of A (2.0 cm) &gt; Amplitude of B (1.0 cm)</p>
<ul>
<li>Therefore, <strong>Sound A is louder</strong> than Sound B</li>
</ul>
<p><strong>Pitch comparison:</strong> - Wavelength of A (4.0 cm) &gt; Wavelength of B (2.0 cm)</p>
<ul>
<li><p>Since <span class="math inline">\(v = f\lambda\)</span> and <span class="math inline">\(v\)</span> is constant, longer wavelength → lower frequency</p></li>
<li><p>Therefore, <strong>Sound A has a lower pitch</strong> than Sound B</p></li>
</ul>
<p><strong>Conclusion:</strong> Sound A is louder but lower-pitched than Sound B.</p>
<hr>
</section>
</section>
<section id="practice-questions" class="level2" data-number="20.9">
<h2 data-number="20.9" class="anchored" data-anchor-id="practice-questions"><span class="header-section-number">20.9</span> Practice Questions</h2>
<section id="core-level" class="level3" data-number="20.9.1">
<h3 data-number="20.9.1" class="anchored" data-anchor-id="core-level"><span class="header-section-number">20.9.1</span> Core Level</h3>
<p><strong>1.</strong> Describe how sound is produced by a vibrating source.</p>
<p><strong>2.</strong> State whether sound waves are transverse or longitudinal. Explain your answer.</p>
<p><strong>3.</strong> State the approximate range of frequencies that can be heard by a healthy human ear.</p>
<p><strong>4.</strong> Explain why sound cannot travel through a vacuum.</p>
<p><strong>5.</strong> State the approximate speed of sound in air.</p>
<p><strong>6.</strong> Describe a method to measure the speed of sound in air using a starting pistol and a stopwatch.</p>
<p><strong>7.</strong> Explain how the amplitude and frequency of a sound wave affect the loudness and pitch of the sound.</p>
<p><strong>8.</strong> Define the term <em>echo</em>.</p>
<p><strong>9.</strong> Define <em>ultrasound</em> and state its frequency range.</p>
<p><strong>10.</strong> A ship uses sonar to measure the depth of the sea. The ultrasound pulse returns after 0.20 s. If the speed of sound in seawater is 1500 m/s, calculate the depth.</p>
</section>
<section id="extended-level" class="level3" data-number="20.9.2">
<h3 data-number="20.9.2" class="anchored" data-anchor-id="extended-level"><span class="header-section-number">20.9.2</span> Extended Level</h3>
<p><strong>11.</strong> Describe, in terms of particle motion, what happens in a compression and a rarefaction of a sound wave.</p>
<p><strong>12.</strong> Explain why sound travels faster in steel than in air, using the kinetic particle model.</p>
<p><strong>13.</strong> Describe how ultrasound is used in non-destructive testing of materials. Include a labelled diagram if helpful.</p>
<p><strong>14.</strong> A bat emits an ultrasound pulse at 50 kHz. The pulse reflects off an insect and returns after 0.02 s. If the speed of sound in air is 340 m/s, calculate the distance to the insect.</p>
<p><strong>15.</strong> Explain why ultrasound is preferred over X-rays for scanning a developing foetus.</p>
<p><strong>16.</strong> Two sound waves have the same amplitude but different frequencies. Compare their loudness and pitch.</p>
<hr>
</section>
</section>
<section id="laboratory-investigation" class="level2" data-number="20.10">
<h2 data-number="20.10" class="anchored" data-anchor-id="laboratory-investigation"><span class="header-section-number">20.10</span> Laboratory Investigation</h2>
<section id="experiment-17.1-measuring-the-speed-of-sound-using-echoes" class="level3" data-number="20.10.1">
<h3 data-number="20.10.1" class="anchored" data-anchor-id="experiment-17.1-measuring-the-speed-of-sound-using-echoes"><span class="header-section-number">20.10.1</span> Experiment 17.1: Measuring the Speed of Sound Using Echoes</h3>
<p><strong>Objective:</strong> To determine the speed of sound in air by measuring the time for an echo to return from a reflecting surface.</p>
<p><strong>Apparatus:</strong> - Two flat wooden boards (to create a sharp clap)</p>
<ul>
<li><p>Stopwatch</p></li>
<li><p>Measuring tape (at least 50 m)</p></li>
<li><p>Large flat wall or building (reflecting surface)</p></li>
</ul>
<p><strong>Variables:</strong> - <strong>Independent:</strong> Distance to reflecting surface</p>
<ul>
<li><p><strong>Dependent:</strong> Time for echo to return</p></li>
<li><p><strong>Controlled:</strong> Same clapping method, same observer timing, same environmental conditions</p></li>
</ul>
<p><strong>Procedure:</strong> 1. Measure and mark a distance <span class="math inline">\(d\)</span> (e.g., 50 m) from a large flat wall.</p>
<ol start="2" type="1">
<li><p>Stand at the marked position facing the wall.</p></li>
<li><p>Clap the two boards together sharply and listen for the echo.</p></li>
<li><p>Practise clapping rhythmically so that each clap coincides with the echo of the previous clap.</p></li>
<li><p>Once a steady rhythm is achieved, have a partner time 20 claps using a stopwatch.</p></li>
<li><p>Record the total time <span class="math inline">\(t_{\text{total}}\)</span> for 20 claps.</p></li>
<li><p>Calculate the time for one round trip: <span class="math inline">\(t = \frac{t_{\text{total}}}{20}\)</span></p></li>
<li><p>Calculate the speed of sound: <span class="math inline">\(v = \frac{2d}{t}\)</span></p></li>
<li><p>Repeat for different distances and calculate an average value.</p></li>
</ol>
<p><strong>Data Table:</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 5%">
<col style="width: 14%">
<col style="width: 32%">
<col style="width: 25%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Trial</th>
<th style="text-align: left;">Distance <span class="math inline">\(d\)</span> (m)</th>
<th style="text-align: left;">Time for 20 claps <span class="math inline">\(t_{\text{total}}\)</span> (s)</th>
<th style="text-align: left;">Time for one round trip <span class="math inline">\(t\)</span> (s)</th>
<th style="text-align: left;">Calculated speed <span class="math inline">\(v\)</span> (m/s)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">50</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;">60</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;">70</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Average</strong></td>
<td style="text-align: left;">—</td>
<td style="text-align: left;">—</td>
<td style="text-align: left;">—</td>
<td style="text-align: left;"><strong><span class="math inline">\(v_{\text{avg}}\)</span> =</strong></td>
</tr>
</tbody>
</table>
<p><strong>Analysis:</strong> 1. Calculate the speed of sound for each trial using <span class="math inline">\(v = \frac{2d}{t}\)</span></p>
<ol start="2" type="1">
<li><p>Calculate the average speed from all trials</p></li>
<li><p>Compare your result with the accepted value (~340 m/s) and discuss possible sources of error</p></li>
</ol>
<p><strong>Precautions:</strong> - ✓ Choose a quiet location to hear echoes clearly</p>
<ul>
<li><p>✓ Ensure the reflecting surface is large and flat for a clear echo</p></li>
<li><p>✓ Practise the clapping rhythm before timing to reduce reaction time errors</p></li>
<li><p>✓ Use a distance of at least 50 m to make timing errors relatively small</p></li>
</ul>
<p><strong>Expected Results:</strong> - The calculated speed should be close to 330–350 m/s, depending on air temperature</p>
<ul>
<li>Repeating at different distances helps identify and reduce systematic errors</li>
</ul>
<p><strong>Conclusion Template:</strong> “The speed of sound in air was determined to be ______ m/s. This value is [close to/different from] the accepted value of 340 m/s, which may be due to [reaction time errors/temperature variations/wind effects/etc.].”</p>
<p><strong>Extension (Supplement):</strong> - Investigate how temperature affects the speed of sound by conducting the experiment at different times of day</p>
<ul>
<li>Compare the speed of sound in different media (e.g., through a metal rod vs.&nbsp;through air)</li>
</ul>
<hr>
</section>
</section>
<section id="exam-style-questions" class="level2" data-number="20.11">
<h2 data-number="20.11" class="anchored" data-anchor-id="exam-style-questions"><span class="header-section-number">20.11</span> Exam-Style Questions</h2>
<section id="paper-1-style-multiple-choice" class="level3" data-number="20.11.1">
<h3 data-number="20.11.1" class="anchored" data-anchor-id="paper-1-style-multiple-choice"><span class="header-section-number">20.11.1</span> Paper 1 Style (Multiple Choice)</h3>
<p><strong>1.</strong> Which statement correctly describes how sound is produced?</p>
<p>A. By vibrating sources in a medium<br>
B. By stationary sources in a vacuum<br>
C. By electromagnetic waves in air<br>
D. By light waves in a medium</p>
<p><strong>2.</strong> Sound waves are longitudinal waves. This means that:</p>
<p>A. The particles vibrate perpendicular to the direction of wave travel<br>
B. The particles vibrate parallel to the direction of wave travel<br>
C. The waves can travel through a vacuum<br>
D. The waves have compressions but no rarefactions</p>
<p><strong>3.</strong> The approximate range of frequencies audible to humans is:</p>
<p>A. 2 Hz to 200 Hz<br>
B. 20 Hz to 2000 Hz<br>
C. 20 Hz to 20 000 Hz<br>
D. 200 Hz to 20 000 Hz</p>
<p><strong>4.</strong> Which statement about the speed of sound is correct?</p>
<p>A. Sound travels fastest in gases<br>
B. Sound travels at the same speed in all media<br>
C. Sound travels faster in solids than in liquids<br>
D. Sound cannot travel through liquids</p>
<p><strong>5.</strong> Ultrasound is defined as sound with a frequency:</p>
<p>A. Below 20 Hz<br>
B. Between 20 Hz and 20 kHz<br>
C. Above 20 kHz<br>
D. Exactly 20 kHz</p>
</section>
<section id="paper-3-style-structured" class="level3" data-number="20.11.2">
<h3 data-number="20.11.2" class="anchored" data-anchor-id="paper-3-style-structured"><span class="header-section-number">20.11.2</span> Paper 3 Style (Structured)</h3>
<p><strong>6.</strong> (a) Describe how sound is produced by a vibrating source. [2]</p>
<ol start="2" type="a">
<li><p>Explain why sound cannot travel through a vacuum. [2]</p></li>
<li><p>State the approximate speed of sound in air. [1]</p></li>
</ol>
<p><strong>7.</strong> (a) Define the terms <em>compression</em> and <em>rarefaction</em> as applied to sound waves. [2]</p>
<ol start="2" type="a">
<li>A student claps her hands 100 m from a large wall. She hears the echo 0.59 s later.</li>
<li>Calculate the speed of sound in air based on this measurement. [3]</li>
</ol>
<ol start="2" type="i">
<li>Suggest one reason why her calculated value might differ from the accepted value. [1]</li>
</ol>
<p><strong>8.</strong> (a) Explain how the amplitude and frequency of a sound wave affect the loudness and pitch of the sound. [3]</p>
<ol start="2" type="a">
<li>A microphone connected to a c.r.o. displays the waveform of a sound. Describe how the display would change if:</li>
<li>the sound became louder but kept the same pitch [2]</li>
</ol>
<ol start="2" type="i">
<li>the sound became higher-pitched but kept the same loudness [2]</li>
</ol>
<p><strong>9.</strong> (Extended) (a) Describe how ultrasound is used in medical scanning of soft tissue. Include reference to how the image is formed. [4]</p>
<ol start="2" type="a">
<li><p>A ship uses sonar to detect a submarine. The ultrasound pulse returns after 0.30 s. If the speed of sound in seawater is 1500 m/s, calculate the distance to the submarine. [3]</p></li>
<li><p>Explain why ultrasound is suitable for measuring distances underwater. [2]</p></li>
</ol>
<hr>
</section>
</section>
<section id="chapter-summary" class="level2" data-number="20.12">
<h2 data-number="20.12" class="anchored" data-anchor-id="chapter-summary"><span class="header-section-number">20.12</span> Chapter Summary</h2>
<section id="key-points-to-remember" class="level3" data-number="20.12.1">
<h3 data-number="20.12.1" class="anchored" data-anchor-id="key-points-to-remember"><span class="header-section-number">20.12.1</span> Key Points to Remember</h3>
<p>✓ <strong>Sound production</strong>: Vibrating sources in a medium produce sound waves<br>
✓ <strong>Longitudinal waves</strong>: Sound consists of compressions and rarefactions; particle vibration ∥ wave propagation<br>
✓ <strong>Audible range</strong>: ~20 Hz to ~20 kHz for healthy human hearing<br>
✓ <strong>Medium required</strong>: Sound cannot travel through a vacuum; needs solid, liquid, or gas<br>
✓ <strong>Speed of sound</strong>: ~330–350 m/s in air; faster in liquids and solids<br>
✓ <strong>Speed measurement</strong>: Use distance–time method with flash and sound<br>
✓ <strong>Loudness</strong>: Depends on amplitude; larger amplitude → louder sound<br>
✓ <strong>Pitch</strong>: Depends on frequency; higher frequency → higher pitch<br>
✓ <strong>Echoes</strong>: Reflection of sound; used to calculate distances: <span class="math inline">\(d = \frac{v \times t}{2}\)</span><br>
✓ <strong>Ultrasound</strong>: Frequency &gt; 20 kHz; used in testing, medical scanning, sonar</p>
</section>
<section id="formulae-sheet" class="level3" data-number="20.12.2">
<h3 data-number="20.12.2" class="anchored" data-anchor-id="formulae-sheet"><span class="header-section-number">20.12.2</span> Formulae Sheet</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 30%">
<col style="width: 36%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Quantity</th>
<th style="text-align: left;">Formula</th>
<th style="text-align: left;">Variables</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Wave speed</td>
<td style="text-align: left;"><span class="math inline">\(v = f\lambda\)</span></td>
<td style="text-align: left;"><span class="math inline">\(v\)</span>=speed (m/s), <span class="math inline">\(f\)</span>=frequency (Hz), <span class="math inline">\(\lambda\)</span>=wavelength (m)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Frequency–period</td>
<td style="text-align: left;"><span class="math inline">\(f = \frac{1}{T}\)</span> or <span class="math inline">\(T = \frac{1}{f}\)</span></td>
<td style="text-align: left;"><span class="math inline">\(T\)</span>=period (s), <span class="math inline">\(f\)</span>=frequency (Hz)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Echo distance</td>
<td style="text-align: left;"><span class="math inline">\(d = \frac{v \times t}{2}\)</span></td>
<td style="text-align: left;"><span class="math inline">\(d\)</span>=distance to reflector (m), <span class="math inline">\(v\)</span>=speed of sound (m/s), <span class="math inline">\(t\)</span>=echo time (s)</td>
</tr>
</tbody>
</table>
<hr>
</section>
</section>
<section id="further-resources" class="level2" data-number="20.13">
<h2 data-number="20.13" class="anchored" data-anchor-id="further-resources"><span class="header-section-number">20.13</span> Further Resources</h2>
<section id="recommended-reading" class="level3" data-number="20.13.1">
<h3 data-number="20.13.1" class="anchored" data-anchor-id="recommended-reading"><span class="header-section-number">20.13.1</span> Recommended Reading</h3>
<ul>
<li><p>Cambridge IGCSE Physics Coursebook, Chapter 14 (Sound)</p></li>
<li><p>Practical Work in Physics: Sound Waves and Ultrasound Experiments</p></li>
</ul>
</section>
<section id="online-resources" class="level3" data-number="20.13.2">
<h3 data-number="20.13.2" class="anchored" data-anchor-id="online-resources"><span class="header-section-number">20.13.2</span> Online Resources</h3>
<ul>
<li><p>PhET Interactive Simulations: Sound, Wave on a String</p></li>
<li><p>BBC Bitesize: Sound Waves, Ultrasound, Echoes</p></li>
<li><p>University of Colorado: Sound wave simulations and visualisations</p></li>
</ul>
</section>
<section id="video-resources" class="level3" data-number="20.13.3">
<h3 data-number="20.13.3" class="anchored" data-anchor-id="video-resources"><span class="header-section-number">20.13.3</span> Video Resources</h3>
<ul>
<li><p>Demonstration: Bell jar experiment showing sound cannot travel in vacuum</p></li>
<li><p>Animation: Particle motion in compressions and rarefactions</p></li>
<li><p>Real-world application: How sonar and medical ultrasound work</p></li>
</ul>
<hr>
</section>
</section>
<section id="glossary" class="level2" data-number="20.14">
<h2 data-number="20.14" class="anchored" data-anchor-id="glossary"><span class="header-section-number">20.14</span> Glossary</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 66%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Term</th>
<th style="text-align: left;">Definition</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Amplitude</strong></td>
<td style="text-align: left;">Maximum displacement of a particle from its rest position; determines loudness of sound</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Audible range</strong></td>
<td style="text-align: left;">Range of frequencies detectable by the human ear (~20 Hz to ~20 kHz)</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Compression</strong></td>
<td style="text-align: left;">Region in a longitudinal sound wave where particles are close together and pressure is high</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Echo</strong></td>
<td style="text-align: left;">Reflection of sound waves from a hard, flat surface; used to calculate distances</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Frequency (<span class="math inline">\(f\)</span>)</strong></td>
<td style="text-align: left;">Number of complete waves (or vibrations) per second; unit: hertz (Hz); determines pitch</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Infrasound</strong></td>
<td style="text-align: left;">Sound with frequency below 20 Hz; inaudible to humans</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Longitudinal wave</strong></td>
<td style="text-align: left;">Wave in which particle vibration is parallel to the direction of wave propagation</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Pitch</strong></td>
<td style="text-align: left;">Perception of how high or low a sound is; determined by frequency</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Rarefaction</strong></td>
<td style="text-align: left;">Region in a longitudinal sound wave where particles are spread apart and pressure is low</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Sonar</strong></td>
<td style="text-align: left;">Sound Navigation and Ranging; uses ultrasound pulses to detect objects and measure distances underwater</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Ultrasound</strong></td>
<td style="text-align: left;">Sound with frequency higher than 20 kHz; inaudible to humans but useful in medical and industrial applications</td>
</tr>
</tbody>
</table>
<hr>
<p><em>End of Chapter 17</em></p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
            // default icon
            link.classList.add("external");
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../chapters/16-em-spectrum.html" class="pagination-link" aria-label="Electromagnetic Spectrum">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Electromagnetic Spectrum</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../chapters/18-magnetism.html" class="pagination-link" aria-label="Simple Phenomena of Magnetism">
        <span class="nav-page-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Simple Phenomena of Magnetism</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>